-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.site_activities (
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(project_id) ON DELETE CASCADE,
    activity_name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    tag TEXT, -- 'Site Work', 'Civil', 'Electrical'
    owner TEXT,
    progress INT DEFAULT 0, -- 0 to 100
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure columns exist (in case table was created previously without them)
ALTER TABLE public.site_activities ADD COLUMN IF NOT EXISTS owner TEXT;
ALTER TABLE public.site_activities ADD COLUMN IF NOT EXISTS tag TEXT;
ALTER TABLE public.site_activities ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0;
ALTER TABLE public.site_activities ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending';

-- Enable RLS (Method varies, but good practice to ensure policies work)
ALTER TABLE public.site_activities ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to allow re-running this script
DROP POLICY IF EXISTS "Enable read access for all users" ON public.site_activities;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.site_activities;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.site_activities;
DROP POLICY IF EXISTS "Enable update for users based on email" ON public.site_activities;
DROP POLICY IF EXISTS "Enable delete for users based on email" ON public.site_activities;
DROP POLICY IF EXISTS "Enable update for public" ON public.site_activities;
DROP POLICY IF EXISTS "Enable delete for public" ON public.site_activities;

-- Policy for viewing activities (Public or Authenticated)
create policy "Enable read access for all users"
on "public"."site_activities"
as PERMISSIVE
for SELECT
to public
using ( true );

-- Policy for inserting activities
create policy "Enable insert for all users"
on "public"."site_activities"
as PERMISSIVE
for INSERT
to public
with check ( true );

-- Policy for updating activities
create policy "Enable update for users based on email"
on "public"."site_activities"
as PERMISSIVE
for UPDATE
to public
using ( true );

-- Policy for deleting activities
create policy "Enable delete for users based on email"
on "public"."site_activities"
as PERMISSIVE
for DELETE
to public
using ( true );
