-- Create table for tracking activity history
CREATE TABLE IF NOT EXISTS public.activity_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.site_activities(activity_id) ON DELETE CASCADE,
    previous_progress INT,
    new_progress INT,
    comment TEXT,
    user_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any to allow re-running
DROP POLICY IF EXISTS "Enable read access for all users" ON public.activity_logs;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.activity_logs;

-- Create policies (Permissive for now based on previous debugging preference)
create policy "Enable read access for all users"
on "public"."activity_logs"
for SELECT
to public
using ( true );

create policy "Enable insert for all users"
on "public"."activity_logs"
for INSERT
to public
with check ( true );
