-- ============================================
-- COMBINED MIGRATIONS FOR MANUAL EXECUTION
-- Generated: 2026-03-01 11:17:52
-- ============================================
-- 
-- INSTRUCTIONS:
-- 1. Go to your Supabase Dashboard
-- 2. Navigate to SQL Editor
-- 3. Copy and paste this entire file
-- 4. Click 'Run' to execute
-- 5. After success, run: npx supabase db push --linked
--
-- ============================================


-- ============================================
-- Migration: 20260208160000_add_lead_estimate_workflow.sql
-- ============================================

-- Lead & Conversion Workflow with Dynamic Estimating
-- Persistent data capture, revisable estimates, automated conversion

-- Update leads table with enhanced status tracking
alter table public.leads
drop constraint if exists leads_status_check;

alter table public.leads
add constraint leads_status_check check (status in (
  'New', 
  'Contacted', 
  'In Progress',
  'Qualified', 
  'Proposal Sent', 
  'Negotiation', 
  'Realized',
  'Unrealized',
  'Won', 
  'Lost'
));

-- Add persistent data capture flag (auto-save everything)
alter table public.leads
add column if not exists data_captured_at timestamp with time zone,
add column if not exists last_activity_at timestamp with time zone default now();

-- Update trigger to mark data as captured immediately
create or replace function public.auto_capture_lead_data()
returns trigger
language plpgsql
as $$
begin
  if new.data_captured_at is null then
    new.data_captured_at := now();
  end if;
  new.last_activity_at := now();
  return new;
end;
$$;

drop trigger if exists trg_auto_capture_lead_data on public.leads;
create trigger trg_auto_capture_lead_data
before insert or update on public.leads
for each row execute function public.auto_capture_lead_data();

-- Estimates Table (Dynamic, Revisable)
create table if not exists public.estimates (
  estimate_id bigint generated by default as identity primary key,
  estimate_number text unique not null,
  lead_id bigint references public.leads(lead_id) on delete cascade not null,
  
  -- Estimate Details
  estimate_name text not null,
  revision_number int default 1 not null,
  status text default 'Draft' check (status in ('Draft', 'Under Review', 'Sent to Client', 'Approved', 'Rejected', 'Revised')) not null,
  
  -- Pricing
  subtotal numeric(15,2) default 0,
  tax_percentage numeric(5,2) default 0,
  tax_amount numeric(15,2) default 0,
  discount_percentage numeric(5,2) default 0,
  discount_amount numeric(15,2) default 0,
  total_amount numeric(15,2) default 0,
  
  -- Dates
  estimate_date date default current_date not null,
  valid_until date,
  approved_date date,
  
  -- Notes
  terms_and_conditions text,
  internal_notes text,
  client_notes text,
  
  -- Approval workflow
  approved_by uuid references auth.users(id),
  approval_notes text,
  
  -- Metadata
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id),
  updated_at timestamp with time zone default now() not null,
  is_active boolean default true
);

-- Estimate Line Items
create table if not exists public.estimate_items (
  item_id bigint generated by default as identity primary key,
  estimate_id bigint references public.estimates(estimate_id) on delete cascade not null,
  
  -- Item Details
  item_number int not null,
  description text not null,
  category text,
  quantity numeric(12,3) not null,
  unit text,
  
  -- Pricing
  unit_price numeric(12,2) not null,
  line_total numeric(15,2) generated always as (quantity * unit_price) stored,
  
  -- Material linking (optional)
  material_id bigint references public.material_master(material_id),
  
  -- Notes
  notes text,
  
  created_at timestamp with time zone default now() not null
);

-- Function: Auto-generate estimate number
create or replace function public.generate_estimate_number()
returns trigger
language plpgsql
as $$
declare
  v_year text;
  v_month text;
  v_sequence int;
  v_estimate_number text;
begin
  v_year := to_char(current_date, 'YYYY');
  v_month := to_char(current_date, 'MM');
  
  -- Get next sequence for this month
  select coalesce(max(
    case 
      when estimate_number ~ ('^EST-' || v_year || v_month || '-[0-9]+$')
      then substring(estimate_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.estimates;
  
  v_estimate_number := 'EST-' || v_year || v_month || '-' || lpad(v_sequence::text, 4, '0');
  new.estimate_number := v_estimate_number;
  
  return new;
end;
$$;

drop trigger if exists trg_generate_estimate_number on public.estimates;
create trigger trg_generate_estimate_number
before insert on public.estimates
for each row 
when (new.estimate_number is null or new.estimate_number = '')
execute function public.generate_estimate_number();

-- Function: Update estimate totals
create or replace function public.update_estimate_totals()
returns trigger
language plpgsql
as $$
declare
  v_subtotal numeric(15,2);
  v_tax_amount numeric(15,2);
  v_discount_amount numeric(15,2);
  v_total numeric(15,2);
begin
  -- Calculate subtotal from all items
  select coalesce(sum(line_total), 0)
  into v_subtotal
  from public.estimate_items
  where estimate_id = coalesce(new.estimate_id, old.estimate_id);
  
  -- Get estimate for tax/discount percentages
  select 
    v_subtotal,
    v_subtotal * (tax_percentage / 100),
    v_subtotal * (discount_percentage / 100)
  into v_subtotal, v_tax_amount, v_discount_amount
  from public.estimates
  where estimate_id = coalesce(new.estimate_id, old.estimate_id);
  
  v_total := v_subtotal + v_tax_amount - v_discount_amount;
  
  -- Update estimate
  update public.estimates
  set 
    subtotal = v_subtotal,
    tax_amount = v_tax_amount,
    discount_amount = v_discount_amount,
    total_amount = v_total,
    updated_at = now()
  where estimate_id = coalesce(new.estimate_id, old.estimate_id);
  
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_update_estimate_totals_insert on public.estimate_items;
create trigger trg_update_estimate_totals_insert
after insert or update or delete on public.estimate_items
for each row execute function public.update_estimate_totals();

-- Function: Automated Conversion Trigger (Estimate Approval â†’ Order + Quotation)
create or replace function public.auto_convert_estimate_to_order()
returns trigger
language plpgsql
as $$
declare
  v_lead record;
  v_project_id bigint;
  v_order_id bigint;
  v_quote_id bigint;
begin
  -- Only trigger on approval
  if new.status = 'Approved' and old.status != 'Approved' then
    
    -- Get lead details
    select * into v_lead
    from public.leads
    where lead_id = new.lead_id;
    
    -- Create Project (if not exists)
    insert into public.projects (
      project_name,
      client_id,
      status,
      start_date,
      estimated_value,
      created_at
    )
    values (
      v_lead.project_name,
      null, -- Will be set from client_name
      'Planning',
      current_date,
      new.total_amount,
      now()
    )
    returning project_id into v_project_id;
    
    -- Create Project Order
    insert into public.project_orders (
      order_number,
      project_id,
      client_name,
      client_email,
      client_phone,
      client_address,
      order_date,
      project_type,
      project_duration,
      estimated_value,
      status,
      source,
      notes,
      converted_from_lead_id,
      created_at
    )
    values (
      'ORD-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('project_orders_order_id_seq')::text, 4, '0'),
      v_project_id,
      v_lead.client_name,
      v_lead.email,
      v_lead.phone,
      v_lead.address,
      current_date,
      v_lead.project_type,
      v_lead.estimated_duration,
      new.total_amount,
      'Confirmed',
      'Lead Conversion',
      'Auto-created from approved estimate: ' || new.estimate_number,
      v_lead.lead_id,
      now()
    )
    returning order_id into v_order_id;
    
    -- Create Quotation from Estimate
    insert into public.quotes (
      quote_number,
      project_id,
      client_name,
      client_email,
      quote_date,
      valid_until,
      subtotal,
      tax_percentage,
      tax_amount,
      discount_amount,
      total,
      status,
      notes,
      created_at
    )
    values (
      'QUO-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('quotes_quote_id_seq')::text, 4, '0'),
      v_project_id,
      v_lead.client_name,
      v_lead.email,
      new.estimate_date,
      new.valid_until,
      new.subtotal,
      new.tax_percentage,
      new.tax_amount,
      new.discount_amount,
      new.total_amount,
      'Accepted',
      'Auto-created from approved estimate: ' || new.estimate_number || '. ' || new.client_notes,
      now()
    )
    returning quote_id into v_quote_id;
    
    -- Copy estimate items to quote items
    insert into public.quote_items (
      quote_id,
      item_number,
      description,
      quantity,
      unit,
      unit_price,
      notes
    )
    select
      v_quote_id,
      item_number,
      description,
      quantity,
      unit,
      unit_price,
      notes
    from public.estimate_items
    where estimate_id = new.estimate_id;
    
    -- Update lead status to Realized/Won
    update public.leads
    set 
      status = 'Realized',
      converted_to_order_id = v_order_id,
      conversion_date = now()
    where lead_id = new.lead_id;
    
    -- Log the conversion
    new.approval_notes := coalesce(new.approval_notes, '') || 
      ' | Auto-converted: Order #' || v_order_id || ', Quote #' || v_quote_id || ', Project #' || v_project_id;
    
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_auto_convert_estimate on public.estimates;
create trigger trg_auto_convert_estimate
before update on public.estimates
for each row execute function public.auto_convert_estimate_to_order();

-- Project Planning Integration: Mandatory fields on conversion
alter table public.projects
add column if not exists schedule_start_date date,
add column if not exists schedule_end_date date,
add column if not exists schedule_notes text,
add column if not exists boq_document_url text,
add column if not exists external_requirements text,
add column if not exists planning_completed boolean default false;

alter table public.project_orders
add column if not exists schedule_start_date date,
add column if not exists schedule_end_date date,
add column if not exists boq_notes text,
add column if not exists external_requirements text;

-- View: Estimates with Lead details
create or replace view public.estimates_with_leads as
select 
  e.*,
  l.client_name,
  l.email as client_email,
  l.phone as client_phone,
  l.project_type,
  l.source as lead_source,
  l.priority,
  l.status as lead_status,
  (select count(*) from public.estimate_items ei where ei.estimate_id = e.estimate_id) as item_count
from public.estimates e
join public.leads l on l.lead_id = e.lead_id;

grant select on public.estimates_with_leads to authenticated;

-- Indexes
create index if not exists idx_estimates_lead on public.estimates(lead_id);
create index if not exists idx_estimates_status on public.estimates(status);
create index if not exists idx_estimates_number on public.estimates(estimate_number);
create index if not exists idx_estimate_items_estimate on public.estimate_items(estimate_id);

-- RLS Policies
alter table public.estimates enable row level security;
alter table public.estimate_items enable row level security;

drop policy if exists "estimates_select_auth" on public.estimates;
create policy "estimates_select_auth"
on public.estimates for select
to authenticated
using (true);

drop policy if exists "estimates_insert_auth" on public.estimates;
create policy "estimates_insert_auth"
on public.estimates for insert
to authenticated
with check (true);

drop policy if exists "estimates_update_auth" on public.estimates;
create policy "estimates_update_auth"
on public.estimates for update
to authenticated
using (true)
with check (true);

drop policy if exists "estimates_delete_auth" on public.estimates;
create policy "estimates_delete_auth"
on public.estimates for delete
to authenticated
using (true);

drop policy if exists "estimate_items_select_auth" on public.estimate_items;
create policy "estimate_items_select_auth"
on public.estimate_items for select
to authenticated
using (true);

drop policy if exists "estimate_items_insert_auth" on public.estimate_items;
create policy "estimate_items_insert_auth"
on public.estimate_items for insert
to authenticated
with check (true);

drop policy if exists "estimate_items_update_auth" on public.estimate_items;
create policy "estimate_items_update_auth"
on public.estimate_items for update
to authenticated
using (true)
with check (true);

drop policy if exists "estimate_items_delete_auth" on public.estimate_items;
create policy "estimate_items_delete_auth"
on public.estimate_items for delete
to authenticated
using (true);

notify pgrst, 'reload schema';



-- ============================================
-- Migration: 20260208170000_add_dynamic_fields.sql
-- ============================================

-- Dynamic Field Configuration System
-- Allow users to add/remove field options for various dropdowns

create table if not exists public.dynamic_field_options (
  option_id bigint generated by default as identity primary key,
  field_type text not null check (field_type in (
    'lead_source',
    'cost_category',
    'payment_method',
    'project_type',
    'material_category',
    'task_priority',
    'other'
  )),
  option_value text not null,
  display_order int default 0,
  is_active boolean default true,
  color_code text,
  description text,
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id),
  updated_at timestamp with time zone default now() not null
);

-- Unique constraint to prevent duplicates
create unique index if not exists idx_dynamic_field_unique 
on public.dynamic_field_options(field_type, option_value) 
where is_active = true;

-- Indexes for performance
create index if not exists idx_dynamic_field_type on public.dynamic_field_options(field_type);
create index if not exists idx_dynamic_field_active on public.dynamic_field_options(is_active);
create index if not exists idx_dynamic_field_order on public.dynamic_field_options(display_order);

-- Insert default values for lead_source
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active)
values 
  ('lead_source', 'Referral', 1, true),
  ('lead_source', 'Website', 2, true),
  ('lead_source', 'Cold Call', 3, true),
  ('lead_source', 'Social Media', 4, true),
  ('lead_source', 'Advertisement', 5, true),
  ('lead_source', 'Walk-in', 6, true),
  ('lead_source', 'Other', 7, true)
on conflict do nothing;

-- Insert default values for cost_category
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active, color_code)
values 
  ('cost_category', 'Material', 1, true, '#3B82F6'),
  ('cost_category', 'Labor', 2, true, '#8B5CF6'),
  ('cost_category', 'Equipment', 3, true, '#F59E0B'),
  ('cost_category', 'Overhead', 4, true, '#10B981'),
  ('cost_category', 'Other', 5, true, '#6B7280')
on conflict do nothing;

-- Insert default values for payment_method
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active)
values 
  ('payment_method', 'Cash', 1, true),
  ('payment_method', 'Cheque', 2, true),
  ('payment_method', 'Bank Transfer', 3, true),
  ('payment_method', 'UPI', 4, true),
  ('payment_method', 'Credit Card', 5, true),
  ('payment_method', 'Other', 6, true)
on conflict do nothing;

-- Insert default values for project_type
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active)
values 
  ('project_type', 'Residential Interior', 1, true),
  ('project_type', 'Commercial Interior', 2, true),
  ('project_type', 'Renovation', 3, true),
  ('project_type', 'Landscaping', 4, true),
  ('project_type', 'Furniture', 5, true),
  ('project_type', 'Consultation', 6, true),
  ('project_type', 'Other', 7, true)
on conflict do nothing;

-- Updated at trigger
create or replace function public.update_dynamic_field_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_dynamic_field_updated_at on public.dynamic_field_options;
create trigger trg_dynamic_field_updated_at
before update on public.dynamic_field_options
for each row execute function public.update_dynamic_field_timestamp();

-- RLS policies
alter table public.dynamic_field_options enable row level security;

drop policy if exists "dynamic_field_options_select_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_select_auth"
on public.dynamic_field_options for select
to authenticated
using (true);

drop policy if exists "dynamic_field_options_insert_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_insert_auth"
on public.dynamic_field_options for insert
to authenticated
with check (true);

drop policy if exists "dynamic_field_options_update_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_update_auth"
on public.dynamic_field_options for update
to authenticated
using (true)
with check (true);

drop policy if exists "dynamic_field_options_delete_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_delete_auth"
on public.dynamic_field_options for delete
to authenticated
using (true);

notify pgrst, 'reload schema';



-- ============================================
-- Migration: 20260208180000_enhance_lead_project_flow.sql
-- ============================================

-- Enhanced Lead to Project Information Flow
-- Ensure comprehensive data transfer and bidirectional linking

-- Add lead reference fields to projects table
alter table public.projects
add column if not exists source_lead_id bigint references public.leads(lead_id),
add column if not exists client_name text,
add column if not exists client_email text,
add column if not exists client_phone text,
add column if not exists client_address text,
add column if not exists project_description text,
add column if not exists project_requirements text;

-- Add project reference to orders
alter table public.project_orders
add column if not exists estimate_id bigint references public.estimates(estimate_id);

-- Add project tracking to estimates
alter table public.estimates
add column if not exists converted_to_project_id bigint references public.projects(project_id),
add column if not exists converted_to_order_id bigint references public.project_orders(order_id),
add column if not exists converted_to_quote_id bigint references public.quotes(quote_id);

-- Enhanced conversion function with complete information flow
create or replace function public.auto_convert_estimate_to_order_enhanced()
returns trigger
language plpgsql
as $$
declare
  v_lead record;
  v_project_id bigint;
  v_order_id bigint;
  v_quote_id bigint;
begin
  -- Only trigger on approval
  if new.status = 'Approved' and old.status != 'Approved' then
    
    -- Get complete lead details
    select * into v_lead
    from public.leads
    where lead_id = new.lead_id;
    
    -- Create Project with full lead information
    insert into public.projects (
      project_name,
      source_lead_id,
      client_name,
      client_email,
      client_phone,
      client_address,
      project_description,
      project_requirements,
      status,
      start_date,
      estimated_value,
      schedule_start_date,
      schedule_end_date,
      created_at
    )
    values (
      coalesce(v_lead.project_name, v_lead.client_name || ' Project'),
      v_lead.lead_id,
      v_lead.client_name,
      v_lead.email,
      v_lead.phone,
      v_lead.address,
      v_lead.description,
      v_lead.requirements,
      'Planning',
      current_date,
      new.total_amount,
      current_date,
      current_date + coalesce(v_lead.estimated_duration_days, 30),
      now()
    )
    returning project_id into v_project_id;
    
    -- Create Project Order with comprehensive details
    insert into public.project_orders (
      order_number,
      project_id,
      estimate_id,
      client_name,
      client_email,
      client_phone,
      client_address,
      order_date,
      project_type,
      project_duration,
      estimated_value,
      schedule_start_date,
      schedule_end_date,
      boq_notes,
      external_requirements,
      status,
      source,
      notes,
      converted_from_lead_id,
      created_at
    )
    values (
      'ORD-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('project_orders_order_id_seq')::text, 4, '0'),
      v_project_id,
      new.estimate_id,
      v_lead.client_name,
      v_lead.email,
      v_lead.phone,
      v_lead.address,
      current_date,
      v_lead.project_type,
      v_lead.estimated_duration_days,
      new.total_amount,
      current_date,
      current_date + coalesce(v_lead.estimated_duration_days, 30),
      'BOQ to be prepared based on estimate line items',
      v_lead.requirements,
      'Confirmed',
      'Lead Conversion - Estimate Approved',
      'Auto-created from approved estimate: ' || new.estimate_number || '. Lead: ' || v_lead.lead_number,
      v_lead.lead_id,
      now()
    )
    returning order_id into v_order_id;
    
    -- Create Quotation from Estimate
    insert into public.quotes (
      quote_number,
      project_id,
      client_name,
      client_email,
      quote_date,
      valid_until,
      subtotal,
      tax_percentage,
      tax_amount,
      discount_amount,
      total,
      status,
      terms_and_conditions,
      notes,
      created_at
    )
    values (
      'QUO-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('quotes_quote_id_seq')::text, 4, '0'),
      v_project_id,
      v_lead.client_name,
      v_lead.email,
      new.estimate_date,
      new.valid_until,
      new.subtotal,
      new.tax_percentage,
      new.tax_amount,
      new.discount_amount,
      new.total_amount,
      'Accepted',
      new.terms_and_conditions,
      'Auto-created from approved estimate: ' || new.estimate_number || '. Client notes: ' || coalesce(new.client_notes, ''),
      now()
    )
    returning quote_id into v_quote_id;
    
    -- Copy estimate items to quote items
    insert into public.quote_items (
      quote_id,
      item_number,
      description,
      quantity,
      unit,
      unit_price,
      notes
    )
    select
      v_quote_id,
      item_number,
      description,
      quantity,
      unit,
      unit_price,
      notes
    from public.estimate_items
    where estimate_id = new.estimate_id
    order by item_number;
    
    -- Update lead status to Realized/Won
    update public.leads
    set 
      status = 'Realized',
      converted_to_order_id = v_order_id,
      conversion_date = now()
    where lead_id = new.lead_id;
    
    -- Update estimate with conversion references
    new.converted_to_project_id := v_project_id;
    new.converted_to_order_id := v_order_id;
    new.converted_to_quote_id := v_quote_id;
    
    -- Log the conversion
    new.approval_notes := coalesce(new.approval_notes, '') || 
      ' | Auto-converted: Project #' || v_project_id || ', Order #' || v_order_id || ', Quote #' || v_quote_id;
    
  end if;
  
  return new;
end;
$$;

-- Replace old trigger with enhanced version
drop trigger if exists trg_auto_convert_estimate on public.estimates;
create trigger trg_auto_convert_estimate
before update on public.estimates
for each row execute function public.auto_convert_estimate_to_order_enhanced();

-- View: Complete lead to project flow tracking
create or replace view public.lead_project_flow as
select 
  l.lead_id,
  l.lead_number,
  l.client_name,
  l.status as lead_status,
  l.estimated_value as lead_estimated_value,
  l.created_at as lead_created_at,
  l.conversion_date,
  
  e.estimate_id,
  e.estimate_number,
  e.status as estimate_status,
  e.total_amount as estimate_total,
  e.approved_date as estimate_approved_date,
  
  p.project_id,
  p.project_name,
  p.status as project_status,
  p.start_date as project_start_date,
  
  po.order_id,
  po.order_number,
  po.status as order_status,
  
  q.quote_id,
  q.quote_number,
  q.status as quote_status,
  
  -- Calculate conversion metrics
  case 
    when l.conversion_date is not null then extract(epoch from (l.conversion_date - l.created_at)) / 86400
    else null
  end as days_to_conversion

from public.leads l
left join public.estimates e on e.lead_id = l.lead_id and e.is_active = true
left join public.projects p on p.source_lead_id = l.lead_id
left join public.project_orders po on po.converted_from_lead_id = l.lead_id
left join public.quotes q on q.project_id = p.project_id;

grant select on public.lead_project_flow to authenticated;

notify pgrst, 'reload schema';



-- ============================================
-- Migration: 20260208190000_add_quote_number_generation.sql
-- ============================================

-- Auto-generate quote numbers with 3-digit format (027, 101, 102, etc.)

-- Function to generate 3-digit quote numbers
create or replace function public.generate_quote_number()
returns trigger
language plpgsql
as $$
declare
  v_sequence int;
  v_quote_number text;
begin
  -- Get the highest existing quote number (extract numeric part)
  select coalesce(max(
    case 
      when quote_number ~ '^[0-9]{3}$' 
      then quote_number::int
      else 0
    end
  ), 26) + 1 -- Start from 27 (next will be 027)
  into v_sequence
  from public.project_quotes;
  
  -- Format as 3-digit with leading zeros
  v_quote_number := lpad(v_sequence::text, 3, '0');
  new.quote_number := v_quote_number;
  
  return new;
end;
$$;

-- Create trigger for auto-generating quote numbers
drop trigger if exists trg_generate_quote_number on public.project_quotes;
create trigger trg_generate_quote_number
before insert on public.project_quotes
for each row 
when (new.quote_number is null or new.quote_number = '')
execute function public.generate_quote_number();

notify pgrst, 'reload schema';



-- ============================================
-- Migration: 20260208200000_add_order_number_generation.sql
-- ============================================

-- Auto-generate order numbers with format: ORD-001, ORD-002, etc.

-- Function to generate order numbers
create or replace function public.generate_order_number()
returns trigger
language plpgsql
as $$
declare
  v_sequence int;
  v_order_number text;
begin
  -- Get the highest existing order number (extract numeric part after ORD-)
  select coalesce(max(
    case 
      when order_number ~ '^ORD-[0-9]+$' 
      then substring(order_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.project_orders;
  
  -- Format as ORD-XXX with leading zeros (3 digits minimum)
  v_order_number := 'ORD-' || lpad(v_sequence::text, 3, '0');
  new.order_number := v_order_number;
  
  return new;
end;
$$;

-- Create trigger for auto-generating order numbers
drop trigger if exists trg_generate_order_number on public.project_orders;
create trigger trg_generate_order_number
before insert on public.project_orders
for each row 
when (new.order_number is null or new.order_number = '')
execute function public.generate_order_number();

notify pgrst, 'reload schema';



-- ============================================
-- Migration: 20260208210000_global_store_inventory_system.sql
-- ============================================

-- Global Store Inventory System
-- Material master with dynamic quantities, material requests with approval, returns workflow

-- Drop old material_master if exists and create new structure
drop table if exists public.material_master cascade;

-- Materials Master (Dynamic list managed by admin)
create table if not exists public.materials_master (
  material_id bigint generated by default as identity primary key,
  material_name text unique not null,
  description text,
  metric text not null check (metric in ('Litres', 'Kgs', 'Tonnes', 'Sqft', 'Metres', 'Units', 'Pieces', 'Boxes', 'Bags')),
  is_active boolean default true,
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Material Quantity Variants (e.g., 20L, 10L, 5L for same material)
create table if not exists public.material_variants (
  variant_id bigint generated by default as identity primary key,
  material_id bigint references public.materials_master(material_id) on delete cascade not null,
  variant_name text not null, -- e.g., "20 Litre Can", "10 Litre Bucket"
  quantity_per_unit numeric(12,3) not null, -- e.g., 20 for 20L can
  is_active boolean default true,
  created_at timestamp with time zone default now() not null
);

-- Store Inventory (Global, Project-independent)
create table if not exists public.store_inventory (
  inventory_id bigint generated by default as identity primary key,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  variant_id bigint references public.material_variants(variant_id) on delete restrict not null,
  number_of_units int not null default 0, -- How many units (cans, bags, etc.)
  total_quantity numeric(12,3) not null default 0, -- Total quantity (e.g., 20L x 5 units = 100L)
  location text,
  notes text,
  last_updated timestamp with time zone default now() not null,
  updated_by uuid references auth.users(id)
);

-- Unique constraint: one row per material-variant combination
create unique index if not exists idx_store_inventory_unique 
on public.store_inventory(material_id, variant_id);

-- Material Requests (from projects)
create table if not exists public.material_requests (
  request_id bigint generated by default as identity primary key,
  request_number text unique not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  
  -- Request details
  requested_quantity numeric(12,3) not null,
  request_source text not null check (request_source in ('Store', 'Local Procurement')),
  priority text default 'Normal' check (priority in ('Urgent', 'High', 'Normal', 'Low')),
  required_by date,
  purpose text,
  
  -- Approval workflow
  status text default 'Pending' not null check (status in ('Pending', 'Approved', 'Rejected', 'Fulfilled', 'Cancelled')),
  approved_by uuid references auth.users(id),
  approved_at timestamp with time zone,
  approval_notes text,
  
  -- Fulfillment tracking
  fulfilled_quantity numeric(12,3),
  fulfilled_at timestamp with time zone,
  fulfillment_notes text,
  
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Material Request Fulfillment Items (which units were used)
create table if not exists public.request_fulfillment_items (
  fulfillment_item_id bigint generated by default as identity primary key,
  request_id bigint references public.material_requests(request_id) on delete cascade not null,
  variant_id bigint references public.material_variants(variant_id) on delete restrict not null,
  units_issued int not null, -- How many units of this variant
  quantity_issued numeric(12,3) not null, -- Total quantity from these units
  issued_at timestamp with time zone default now() not null,
  issued_by uuid references auth.users(id)
);

-- Material Returns (from projects back to store)
create table if not exists public.material_returns (
  return_id bigint generated by default as identity primary key,
  return_number text unique not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  variant_id bigint references public.material_variants(variant_id),
  
  -- Return details
  returned_quantity numeric(12,3) not null,
  number_of_units int,
  condition text check (condition in ('Excellent', 'Good', 'Fair', 'Damaged', 'Unusable')),
  reason text,
  
  -- Store approval workflow
  status text default 'Pending' not null check (status in ('Pending', 'Accepted', 'Rejected')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamp with time zone,
  review_notes text,
  
  -- Original request reference
  source_request_id bigint references public.material_requests(request_id),
  
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Material Movement Logs (Complete audit trail)
create table if not exists public.material_movement_logs (
  log_id bigint generated by default as identity primary key,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  variant_id bigint references public.material_variants(variant_id),
  
  -- Movement details
  movement_type text not null check (movement_type in ('Store In', 'Store Out', 'Project In', 'Project Out', 'Return to Store', 'Local Procurement')),
  project_id bigint references public.projects(project_id),
  quantity numeric(12,3) not null,
  number_of_units int,
  
  -- References
  reference_type text check (reference_type in ('Material Request', 'Material Return', 'Manual Adjustment', 'Initial Stock')),
  reference_id bigint,
  
  -- Additional info
  notes text,
  movement_date timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Auto-generate request numbers
create or replace function public.generate_request_number()
returns trigger
language plpgsql
as $$
declare
  v_sequence int;
  v_request_number text;
begin
  select coalesce(max(
    case 
      when request_number ~ '^MR-[0-9]+$' 
      then substring(request_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.material_requests;
  
  v_request_number := 'MR-' || lpad(v_sequence::text, 4, '0');
  new.request_number := v_request_number;
  
  return new;
end;
$$;

drop trigger if exists trg_generate_request_number on public.material_requests;
create trigger trg_generate_request_number
before insert on public.material_requests
for each row 
when (new.request_number is null or new.request_number = '')
execute function public.generate_request_number();

-- Auto-generate return numbers
create or replace function public.generate_return_number()
returns trigger
language plpgsql
as $$
declare
  v_sequence int;
  v_return_number text;
begin
  select coalesce(max(
    case 
      when return_number ~ '^RTN-[0-9]+$' 
      then substring(return_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.material_returns;
  
  v_return_number := 'RTN-' || lpad(v_sequence::text, 4, '0');
  new.return_number := v_return_number;
  
  return new;
end;
$$;

drop trigger if exists trg_generate_return_number on public.material_returns;
create trigger trg_generate_return_number
before insert on public.material_returns
for each row 
when (new.return_number is null or new.return_number = '')
execute function public.generate_return_number();

-- Function: Update store inventory when request fulfilled
create or replace function public.update_store_inventory_on_fulfillment()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'Fulfilled' and old.status != 'Fulfilled' then
    -- Log the movement
    insert into public.material_movement_logs (
      material_id,
      movement_type,
      project_id,
      quantity,
      reference_type,
      reference_id,
      notes,
      created_by
    ) values (
      new.material_id,
      case when new.request_source = 'Store' then 'Store Out' else 'Local Procurement' end,
      new.project_id,
      new.fulfilled_quantity,
      'Material Request',
      new.request_id,
      'Fulfilled request: ' || new.request_number,
      new.approved_by
    );
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_update_inventory_on_fulfillment on public.material_requests;
create trigger trg_update_inventory_on_fulfillment
after update on public.material_requests
for each row execute function public.update_store_inventory_on_fulfillment();

-- Function: Handle material returns to store
create or replace function public.handle_material_return_to_store()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'Accepted' and old.status = 'Pending' then
    -- Add back to store inventory if variant specified
    if new.variant_id is not null then
      insert into public.store_inventory (
        material_id,
        variant_id,
        number_of_units,
        total_quantity,
        notes
      ) values (
        new.material_id,
        new.variant_id,
        coalesce(new.number_of_units, 0),
        new.returned_quantity,
        'Returned from project via ' || new.return_number
      )
      on conflict (material_id, variant_id) 
      do update set
        number_of_units = store_inventory.number_of_units + excluded.number_of_units,
        total_quantity = store_inventory.total_quantity + excluded.total_quantity,
        last_updated = now();
    end if;
    
    -- Log the movement
    insert into public.material_movement_logs (
      material_id,
      variant_id,
      movement_type,
      project_id,
      quantity,
      number_of_units,
      reference_type,
      reference_id,
      notes,
      created_by
    ) values (
      new.material_id,
      new.variant_id,
      'Return to Store',
      new.project_id,
      new.returned_quantity,
      new.number_of_units,
      'Material Return',
      new.return_id,
      'Accepted return: ' || new.return_number,
      new.reviewed_by
    );
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_handle_return_to_store on public.material_returns;
create trigger trg_handle_return_to_store
after update on public.material_returns
for each row execute function public.handle_material_return_to_store();

-- Indexes
create index if not exists idx_materials_master_name on public.materials_master(material_name);
create index if not exists idx_material_variants_material on public.material_variants(material_id);
create index if not exists idx_store_inventory_material on public.store_inventory(material_id);
create index if not exists idx_material_requests_project on public.material_requests(project_id);
create index if not exists idx_material_requests_status on public.material_requests(status);
create index if not exists idx_material_returns_project on public.material_returns(project_id);
create index if not exists idx_material_returns_status on public.material_returns(status);
create index if not exists idx_movement_logs_material on public.material_movement_logs(material_id);
create index if not exists idx_movement_logs_project on public.material_movement_logs(project_id);

-- RLS Policies
alter table public.materials_master enable row level security;
alter table public.material_variants enable row level security;
alter table public.store_inventory enable row level security;
alter table public.material_requests enable row level security;
alter table public.request_fulfillment_items enable row level security;
alter table public.material_returns enable row level security;
alter table public.material_movement_logs enable row level security;

-- Materials Master
drop policy if exists "materials_master_select_auth" on public.materials_master;
create policy "materials_master_select_auth" on public.materials_master for select to authenticated using (true);

drop policy if exists "materials_master_insert_auth" on public.materials_master;
create policy "materials_master_insert_auth" on public.materials_master for insert to authenticated with check (true);

drop policy if exists "materials_master_update_auth" on public.materials_master;
create policy "materials_master_update_auth" on public.materials_master for update to authenticated using (true);

drop policy if exists "materials_master_delete_auth" on public.materials_master;
create policy "materials_master_delete_auth" on public.materials_master for delete to authenticated using (true);

-- Material Variants
drop policy if exists "material_variants_select_auth" on public.material_variants;
create policy "material_variants_select_auth" on public.material_variants for select to authenticated using (true);

drop policy if exists "material_variants_insert_auth" on public.material_variants;
create policy "material_variants_insert_auth" on public.material_variants for insert to authenticated with check (true);

drop policy if exists "material_variants_update_auth" on public.material_variants;
create policy "material_variants_update_auth" on public.material_variants for update to authenticated using (true);

drop policy if exists "material_variants_delete_auth" on public.material_variants;
create policy "material_variants_delete_auth" on public.material_variants for delete to authenticated using (true);

-- Store Inventory
drop policy if exists "store_inventory_select_auth" on public.store_inventory;
create policy "store_inventory_select_auth" on public.store_inventory for select to authenticated using (true);

drop policy if exists "store_inventory_insert_auth" on public.store_inventory;
create policy "store_inventory_insert_auth" on public.store_inventory for insert to authenticated with check (true);

drop policy if exists "store_inventory_update_auth" on public.store_inventory;
create policy "store_inventory_update_auth" on public.store_inventory for update to authenticated using (true);

drop policy if exists "store_inventory_delete_auth" on public.store_inventory;
create policy "store_inventory_delete_auth" on public.store_inventory for delete to authenticated using (true);

-- Material Requests (all policies)
drop policy if exists "material_requests_select_auth" on public.material_requests;
create policy "material_requests_select_auth" on public.material_requests for select to authenticated using (true);

drop policy if exists "material_requests_insert_auth" on public.material_requests;
create policy "material_requests_insert_auth" on public.material_requests for insert to authenticated with check (true);

drop policy if exists "material_requests_update_auth" on public.material_requests;
create policy "material_requests_update_auth" on public.material_requests for update to authenticated using (true);

drop policy if exists "material_requests_delete_auth" on public.material_requests;
create policy "material_requests_delete_auth" on public.material_requests for delete to authenticated using (true);

-- Request Fulfillment Items
drop policy if exists "request_fulfillment_items_select_auth" on public.request_fulfillment_items;
create policy "request_fulfillment_items_select_auth" on public.request_fulfillment_items for select to authenticated using (true);

drop policy if exists "request_fulfillment_items_insert_auth" on public.request_fulfillment_items;
create policy "request_fulfillment_items_insert_auth" on public.request_fulfillment_items for insert to authenticated with check (true);

-- Material Returns (all policies)
drop policy if exists "material_returns_select_auth" on public.material_returns;
create policy "material_returns_select_auth" on public.material_returns for select to authenticated using (true);

drop policy if exists "material_returns_insert_auth" on public.material_returns;
create policy "material_returns_insert_auth" on public.material_returns for insert to authenticated with check (true);

drop policy if exists "material_returns_update_auth" on public.material_returns;
create policy "material_returns_update_auth" on public.material_returns for update to authenticated using (true);

drop policy if exists "material_returns_delete_auth" on public.material_returns;
create policy "material_returns_delete_auth" on public.material_returns for delete to authenticated using (true);

-- Movement Logs
drop policy if exists "material_movement_logs_select_auth" on public.material_movement_logs;
create policy "material_movement_logs_select_auth" on public.material_movement_logs for select to authenticated using (true);

drop policy if exists "material_movement_logs_insert_auth" on public.material_movement_logs;
create policy "material_movement_logs_insert_auth" on public.material_movement_logs for insert to authenticated with check (true);

notify pgrst, 'reload schema';



-- ============================================
-- Migration: 20260208_add_attendance_and_leaves.sql
-- ============================================

-- Attendance (check-in/out) + Leave requests

create table if not exists public.attendance_logs (
  attendance_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(user_id) on delete cascade not null,
  work_date date not null default (timezone('utc'::text, now()))::date,

  check_in_at timestamp with time zone,
  check_in_lat numeric,
  check_in_lng numeric,
  check_in_accuracy numeric,
  check_in_photo_path text,

  check_out_at timestamp with time zone,
  check_out_lat numeric,
  check_out_lng numeric,
  check_out_accuracy numeric,
  check_out_photo_path text,

  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- One log per user per day
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'attendance_logs_user_day_unique'
  ) then
    alter table public.attendance_logs
      add constraint attendance_logs_user_day_unique unique (user_id, work_date);
  end if;
end $$;

create index if not exists idx_attendance_logs_user_date
  on public.attendance_logs (user_id, work_date desc);

drop trigger if exists trg_attendance_logs_updated_at on public.attendance_logs;
create trigger trg_attendance_logs_updated_at
before update on public.attendance_logs
for each row execute function public.set_updated_at();

create table if not exists public.leave_requests (
  leave_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(user_id) on delete cascade not null,
  start_date date not null,
  end_date date not null,
  leave_type text default 'Leave' not null,
  reason text,
  status text default 'Pending' not null,
  approved_by uuid references public.profiles(user_id),
  approved_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Basic status constraint (idempotent-ish)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'leave_requests_status_check'
  ) then
    alter table public.leave_requests
      add constraint leave_requests_status_check
      check (status in ('Pending', 'Approved', 'Rejected'));
  end if;
end $$;

create index if not exists idx_leave_requests_user_dates
  on public.leave_requests (user_id, start_date desc, end_date desc);

drop trigger if exists trg_leave_requests_updated_at on public.leave_requests;
create trigger trg_leave_requests_updated_at
before update on public.leave_requests
for each row execute function public.set_updated_at();

-- RLS
alter table if exists public.attendance_logs enable row level security;
alter table if exists public.leave_requests enable row level security;

-- Attendance policies (self only)
drop policy if exists "attendance_logs_select_own" on public.attendance_logs;
drop policy if exists "attendance_logs_insert_own" on public.attendance_logs;
drop policy if exists "attendance_logs_update_own" on public.attendance_logs;
drop policy if exists "attendance_logs_delete_own" on public.attendance_logs;

create policy "attendance_logs_select_own"
on public.attendance_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "attendance_logs_insert_own"
on public.attendance_logs for insert
to authenticated
with check (auth.uid() = user_id);

create policy "attendance_logs_update_own"
on public.attendance_logs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Leave policies (self only; approvals happen via service-role API)
drop policy if exists "leave_requests_select_own" on public.leave_requests;
drop policy if exists "leave_requests_insert_own" on public.leave_requests;
drop policy if exists "leave_requests_update_own" on public.leave_requests;
drop policy if exists "leave_requests_delete_own" on public.leave_requests;

create policy "leave_requests_select_own"
on public.leave_requests for select
to authenticated
using (auth.uid() = user_id);

create policy "leave_requests_insert_own"
on public.leave_requests for insert
to authenticated
with check (auth.uid() = user_id);

create policy "leave_requests_update_own"
on public.leave_requests for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "leave_requests_delete_own"
on public.leave_requests for delete
to authenticated
using (auth.uid() = user_id);

notify pgrst, 'reload schema';



