-- Core & Auth
CREATE TABLE public.profiles (
    user_id UUID REFERENCES auth.users(id) PRIMARY KEY,
    full_name TEXT,
    role TEXT CHECK (role IN ('Admin', 'ProjectManager', 'SiteSupervisor', 'Client', 'Vendor')),
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name TEXT NOT NULL,
    client_id UUID REFERENCES public.profiles(user_id),
    start_date DATE,
    status TEXT CHECK (status IN ('Planning', 'Execution', 'Handover', 'Completed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Planning & Execution (The Site Loop)
CREATE TABLE public.activities (
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(project_id),
    name TEXT NOT NULL,
    start_date DATE,
    internal_duration_days INT,
    client_buffer_days INT,
    completion_percentage INT DEFAULT 0,
    status TEXT DEFAULT 'Not Started'
);

CREATE TABLE public.site_updates (
    update_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.activities(activity_id),
    reported_by UUID REFERENCES public.profiles(user_id),
    
    -- Evidence
    audio_url TEXT, -- Link to Supabase Storage bucket 'audio-logs'
    transcript_text TEXT,
    remarks TEXT,
    
    progress_claimed_pct INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Resource Management
CREATE TABLE public.material_master (
    material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    unit TEXT
);

CREATE TABLE public.purchase_requests (
    pr_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(project_id),
    requester_id UUID REFERENCES public.profiles(user_id),
    status TEXT CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.pr_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id BIGINT REFERENCES public.purchase_requests(pr_id),
    material_id BIGINT REFERENCES public.material_master(material_id),
    requested_qty DECIMAL,
    approved_qty DECIMAL -- Edited by PM
);

CREATE TABLE public.goods_received (
    grn_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id BIGINT REFERENCES public.purchase_requests(pr_id),
    received_by UUID REFERENCES public.profiles(user_id),
    received_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Financials
CREATE TABLE public.transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(project_id),
    type TEXT CHECK (type IN ('Credit', 'Debit')),
    category TEXT CHECK (category IN ('ClientPayment', 'VendorPayment', 'LabourPayout')),
    amount DECIMAL(15,2),
    payment_channel TEXT, -- UPI, NEFT, Cash
    receipt_url TEXT, -- Link to Supabase Storage bucket 'documents'
    transaction_date DATE
);
