CREATE TABLE public.site_activities (
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(project_id) ON DELETE CASCADE,
    activity_name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    tag TEXT, -- 'Site Work', 'Civil', 'Electrical'
    owner TEXT, -- 'Nikhil Kaushik'
    progress INT DEFAULT 0, -- 0 to 100
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
