-- Attendance (check-in/out) + Leave requests

create table if not exists public.attendance_logs (
  attendance_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(user_id) on delete cascade not null,
  work_date date not null default (timezone('utc'::text, now()))::date,

  check_in_at timestamp with time zone,
  check_in_lat numeric,
  check_in_lng numeric,
  check_in_accuracy numeric,
  check_in_photo_path text,

  check_out_at timestamp with time zone,
  check_out_lat numeric,
  check_out_lng numeric,
  check_out_accuracy numeric,
  check_out_photo_path text,

  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- One log per user per day
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'attendance_logs_user_day_unique'
  ) then
    alter table public.attendance_logs
      add constraint attendance_logs_user_day_unique unique (user_id, work_date);
  end if;
end $$;

create index if not exists idx_attendance_logs_user_date
  on public.attendance_logs (user_id, work_date desc);

drop trigger if exists trg_attendance_logs_updated_at on public.attendance_logs;
create trigger trg_attendance_logs_updated_at
before update on public.attendance_logs
for each row execute function public.set_updated_at();

create table if not exists public.leave_requests (
  leave_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(user_id) on delete cascade not null,
  start_date date not null,
  end_date date not null,
  leave_type text default 'Leave' not null,
  reason text,
  status text default 'Pending' not null,
  approved_by uuid references public.profiles(user_id),
  approved_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Basic status constraint (idempotent-ish)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'leave_requests_status_check'
  ) then
    alter table public.leave_requests
      add constraint leave_requests_status_check
      check (status in ('Pending', 'Approved', 'Rejected'));
  end if;
end $$;

create index if not exists idx_leave_requests_user_dates
  on public.leave_requests (user_id, start_date desc, end_date desc);

drop trigger if exists trg_leave_requests_updated_at on public.leave_requests;
create trigger trg_leave_requests_updated_at
before update on public.leave_requests
for each row execute function public.set_updated_at();

-- RLS
alter table if exists public.attendance_logs enable row level security;
alter table if exists public.leave_requests enable row level security;

-- Attendance policies (self only)
drop policy if exists "attendance_logs_select_own" on public.attendance_logs;
drop policy if exists "attendance_logs_insert_own" on public.attendance_logs;
drop policy if exists "attendance_logs_update_own" on public.attendance_logs;
drop policy if exists "attendance_logs_delete_own" on public.attendance_logs;

create policy "attendance_logs_select_own"
on public.attendance_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "attendance_logs_insert_own"
on public.attendance_logs for insert
to authenticated
with check (auth.uid() = user_id);

create policy "attendance_logs_update_own"
on public.attendance_logs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Leave policies (self only; approvals happen via service-role API)
drop policy if exists "leave_requests_select_own" on public.leave_requests;
drop policy if exists "leave_requests_insert_own" on public.leave_requests;
drop policy if exists "leave_requests_update_own" on public.leave_requests;
drop policy if exists "leave_requests_delete_own" on public.leave_requests;

create policy "leave_requests_select_own"
on public.leave_requests for select
to authenticated
using (auth.uid() = user_id);

create policy "leave_requests_insert_own"
on public.leave_requests for insert
to authenticated
with check (auth.uid() = user_id);

create policy "leave_requests_update_own"
on public.leave_requests for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "leave_requests_delete_own"
on public.leave_requests for delete
to authenticated
using (auth.uid() = user_id);

notify pgrst, 'reload schema';

