-- Dynamic Field Configuration System
-- Allow users to add/remove field options for various dropdowns

create table if not exists public.dynamic_field_options (
  option_id bigint generated by default as identity primary key,
  field_type text not null check (field_type in (
    'lead_source',
    'cost_category',
    'payment_method',
    'project_type',
    'material_category',
    'task_priority',
    'other'
  )),
  option_value text not null,
  display_order int default 0,
  is_active boolean default true,
  color_code text,
  description text,
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id),
  updated_at timestamp with time zone default now() not null
);

-- Unique constraint to prevent duplicates
create unique index if not exists idx_dynamic_field_unique 
on public.dynamic_field_options(field_type, option_value) 
where is_active = true;

-- Indexes for performance
create index if not exists idx_dynamic_field_type on public.dynamic_field_options(field_type);
create index if not exists idx_dynamic_field_active on public.dynamic_field_options(is_active);
create index if not exists idx_dynamic_field_order on public.dynamic_field_options(display_order);

-- Insert default values for lead_source
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active)
values 
  ('lead_source', 'Referral', 1, true),
  ('lead_source', 'Website', 2, true),
  ('lead_source', 'Cold Call', 3, true),
  ('lead_source', 'Social Media', 4, true),
  ('lead_source', 'Advertisement', 5, true),
  ('lead_source', 'Walk-in', 6, true),
  ('lead_source', 'Other', 7, true)
on conflict do nothing;

-- Insert default values for cost_category
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active, color_code)
values 
  ('cost_category', 'Material', 1, true, '#3B82F6'),
  ('cost_category', 'Labor', 2, true, '#8B5CF6'),
  ('cost_category', 'Equipment', 3, true, '#F59E0B'),
  ('cost_category', 'Overhead', 4, true, '#10B981'),
  ('cost_category', 'Other', 5, true, '#6B7280')
on conflict do nothing;

-- Insert default values for payment_method
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active)
values 
  ('payment_method', 'Cash', 1, true),
  ('payment_method', 'Cheque', 2, true),
  ('payment_method', 'Bank Transfer', 3, true),
  ('payment_method', 'UPI', 4, true),
  ('payment_method', 'Credit Card', 5, true),
  ('payment_method', 'Other', 6, true)
on conflict do nothing;

-- Insert default values for project_type
insert into public.dynamic_field_options (field_type, option_value, display_order, is_active)
values 
  ('project_type', 'Residential Interior', 1, true),
  ('project_type', 'Commercial Interior', 2, true),
  ('project_type', 'Renovation', 3, true),
  ('project_type', 'Landscaping', 4, true),
  ('project_type', 'Furniture', 5, true),
  ('project_type', 'Consultation', 6, true),
  ('project_type', 'Other', 7, true)
on conflict do nothing;

-- Updated at trigger
create or replace function public.update_dynamic_field_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_dynamic_field_updated_at on public.dynamic_field_options;
create trigger trg_dynamic_field_updated_at
before update on public.dynamic_field_options
for each row execute function public.update_dynamic_field_timestamp();

-- RLS policies
alter table public.dynamic_field_options enable row level security;

drop policy if exists "dynamic_field_options_select_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_select_auth"
on public.dynamic_field_options for select
to authenticated
using (true);

drop policy if exists "dynamic_field_options_insert_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_insert_auth"
on public.dynamic_field_options for insert
to authenticated
with check (true);

drop policy if exists "dynamic_field_options_update_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_update_auth"
on public.dynamic_field_options for update
to authenticated
using (true)
with check (true);

drop policy if exists "dynamic_field_options_delete_auth" on public.dynamic_field_options;
create policy "dynamic_field_options_delete_auth"
on public.dynamic_field_options for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
