create table if not exists public.client_updates (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  image_url text,
  description text,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

-- RLS Policies
alter table public.client_updates enable row level security;

create policy "Enable read access for authenticated users"
on public.client_updates for select
to authenticated
using (true);

create policy "Enable insert access for authenticated users"
on public.client_updates for insert
to authenticated
with check (true);

create policy "Enable update access for authenticated users"
on public.client_updates for update
to authenticated
using (true);

create policy "Enable delete access for authenticated users"
on public.client_updates for delete
to authenticated
using (true);
