-- Payments made to manpower (with optional UPI/bank screenshot) for reconciliation vs estimated earnings.

create table if not exists public.manpower_payments (
  payment_id bigint generated by default as identity primary key,
  labour_id bigint not null references public.labour_master(id) on delete cascade,
  project_id bigint references public.projects(project_id) on delete set null,
  amount numeric(14,2) not null check (amount > 0),
  payment_date date not null default current_date,
  notes text,
  screenshot_path text,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_manpower_payments_labour on public.manpower_payments(labour_id);
create index if not exists idx_manpower_payments_project on public.manpower_payments(project_id);
create index if not exists idx_manpower_payments_date on public.manpower_payments(payment_date);

alter table public.manpower_payments enable row level security;

drop policy if exists "manpower_payments_select_auth" on public.manpower_payments;
create policy "manpower_payments_select_auth"
  on public.manpower_payments for select to authenticated using (true);

drop policy if exists "manpower_payments_insert_auth" on public.manpower_payments;
create policy "manpower_payments_insert_auth"
  on public.manpower_payments for insert to authenticated with check (true);

drop policy if exists "manpower_payments_update_auth" on public.manpower_payments;
create policy "manpower_payments_update_auth"
  on public.manpower_payments for update to authenticated using (true) with check (true);

drop policy if exists "manpower_payments_delete_auth" on public.manpower_payments;
create policy "manpower_payments_delete_auth"
  on public.manpower_payments for delete to authenticated using (true);

-- Private bucket for payment screenshots
insert into storage.buckets (id, name, public)
values ('manpower-payments', 'manpower-payments', false)
on conflict (id) do nothing;

drop policy if exists "Manpower payments: Authenticated Read" on storage.objects;
drop policy if exists "Manpower payments: Authenticated Upload" on storage.objects;
drop policy if exists "Manpower payments: Authenticated Update" on storage.objects;
drop policy if exists "Manpower payments: Authenticated Delete" on storage.objects;

create policy "Manpower payments: Authenticated Read"
  on storage.objects for select to authenticated
  using (bucket_id = 'manpower-payments' and auth.role() = 'authenticated');

create policy "Manpower payments: Authenticated Upload"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'manpower-payments' and auth.role() = 'authenticated');

create policy "Manpower payments: Authenticated Update"
  on storage.objects for update to authenticated
  using (bucket_id = 'manpower-payments' and auth.role() = 'authenticated');

create policy "Manpower payments: Authenticated Delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'manpower-payments' and auth.role() = 'authenticated');

notify pgrst, 'reload schema';
