-- Outsourced Labor Payment Tracking
-- Track advance payments and final settlements

create table if not exists public.outsourced_payments (
  payment_id bigint generated by default as identity primary key,
  manpower_id bigint references public.project_manpower(id) on delete cascade not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  payment_type text not null check (payment_type in ('Advance', 'Settlement', 'Partial')),
  payment_date date not null default current_date,
  amount numeric(12,2) not null check (amount >= 0),
  payment_method text,
  reference_number text,
  notes text,
  approved_by uuid references auth.users(id),
  approved_at timestamp with time zone,
  status text default 'Pending' not null check (status in ('Pending', 'Approved', 'Paid', 'Rejected')),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Indexes for performance
create index if not exists idx_outsourced_payments_manpower on public.outsourced_payments(manpower_id);
create index if not exists idx_outsourced_payments_project on public.outsourced_payments(project_id);
create index if not exists idx_outsourced_payments_type on public.outsourced_payments(payment_type);
create index if not exists idx_outsourced_payments_status on public.outsourced_payments(status);

-- Updated at trigger
drop trigger if exists trg_outsourced_payments_updated_at on public.outsourced_payments;
create trigger trg_outsourced_payments_updated_at
before update on public.outsourced_payments
for each row execute function public.set_updated_at();

-- RLS policies
alter table public.outsourced_payments enable row level security;

drop policy if exists "outsourced_payments_select_auth" on public.outsourced_payments;
create policy "outsourced_payments_select_auth"
on public.outsourced_payments for select
to authenticated
using (true);

drop policy if exists "outsourced_payments_insert_auth" on public.outsourced_payments;
create policy "outsourced_payments_insert_auth"
on public.outsourced_payments for insert
to authenticated
with check (true);

drop policy if exists "outsourced_payments_update_auth" on public.outsourced_payments;
create policy "outsourced_payments_update_auth"
on public.outsourced_payments for update
to authenticated
using (true)
with check (true);

drop policy if exists "outsourced_payments_delete_auth" on public.outsourced_payments;
create policy "outsourced_payments_delete_auth"
on public.outsourced_payments for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
