-- Labour Master: global registry of In-House employees and Outsourced contractors
create table if not exists public.labour_master (
  id bigint generated by default as identity primary key,
  name text not null,
  labour_type text not null check (labour_type in ('In-House', 'Outsourced')),
  designation text,
  monthly_salary numeric(12,2),   -- only for In-House; leave null for Outsourced
  phone text,
  notes text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

drop trigger if exists trg_labour_master_updated_at on public.labour_master;
create trigger trg_labour_master_updated_at
before update on public.labour_master
for each row execute function public.set_updated_at();

-- RLS
alter table public.labour_master enable row level security;

drop policy if exists "labour_master_select_auth"  on public.labour_master;
drop policy if exists "labour_master_insert_admin" on public.labour_master;
drop policy if exists "labour_master_update_admin" on public.labour_master;
drop policy if exists "labour_master_delete_admin" on public.labour_master;

create policy "labour_master_select_auth"
  on public.labour_master for select to authenticated using (true);

create policy "labour_master_insert_admin"
  on public.labour_master for insert to authenticated
  with check (exists (select 1 from public.profiles where user_id = auth.uid() and role in ('Admin','ProjectManager')));

create policy "labour_master_update_admin"
  on public.labour_master for update to authenticated
  using (exists (select 1 from public.profiles where user_id = auth.uid() and role in ('Admin','ProjectManager')));

create policy "labour_master_delete_admin"
  on public.labour_master for delete to authenticated
  using (exists (select 1 from public.profiles where user_id = auth.uid() and role in ('Admin','ProjectManager')));

-- Add labour tracking columns to project_manpower
-- (previous migration may have already added labor_type etc — all are idempotent)
alter table public.project_manpower
  add column if not exists labour_id    bigint references public.labour_master(id) on delete set null,
  add column if not exists bandwidth_pct numeric(5,2)  check (bandwidth_pct  >= 0 and bandwidth_pct  <= 100),
  add column if not exists daily_wage   numeric(12,2) check (daily_wage   >= 0),
  add column if not exists incentive    numeric(12,2) default 0 check (incentive >= 0);

notify pgrst, 'reload schema';
