-- Ensure site_activities is compatible with UI + safe for authenticated CRUD.
-- Also ensure activity_logs exists for ActivityDetailsDialog history.

-- Columns (idempotent)
alter table if exists public.site_activities
  add column if not exists description text;

alter table if exists public.site_activities
  add column if not exists dependencies text;

-- Activity logs table (idempotent)
create table if not exists public.activity_logs (
  log_id bigint generated by default as identity primary key,
  activity_id bigint references public.site_activities(activity_id) on delete cascade not null,
  previous_progress int,
  new_progress int,
  comment text,
  user_name text,
  created_at timestamp with time zone default now()
);

-- RLS (safe defaults)
alter table if exists public.site_activities enable row level security;
alter table if exists public.activity_logs enable row level security;

-- Policies (drop + recreate to stay idempotent)
drop policy if exists "site_activities_select_auth" on public.site_activities;
drop policy if exists "site_activities_insert_auth" on public.site_activities;
drop policy if exists "site_activities_update_auth" on public.site_activities;
drop policy if exists "site_activities_delete_auth" on public.site_activities;

create policy "site_activities_select_auth"
on public.site_activities for select
to authenticated
using (true);

create policy "site_activities_insert_auth"
on public.site_activities for insert
to authenticated
with check (true);

create policy "site_activities_update_auth"
on public.site_activities for update
to authenticated
using (true)
with check (true);

create policy "site_activities_delete_auth"
on public.site_activities for delete
to authenticated
using (true);

drop policy if exists "activity_logs_select_auth" on public.activity_logs;
drop policy if exists "activity_logs_insert_auth" on public.activity_logs;
drop policy if exists "activity_logs_update_auth" on public.activity_logs;
drop policy if exists "activity_logs_delete_auth" on public.activity_logs;

create policy "activity_logs_select_auth"
on public.activity_logs for select
to authenticated
using (true);

create policy "activity_logs_insert_auth"
on public.activity_logs for insert
to authenticated
with check (true);

-- Usually logs are append-only; we still allow update/delete for now.
create policy "activity_logs_update_auth"
on public.activity_logs for update
to authenticated
using (true)
with check (true);

create policy "activity_logs_delete_auth"
on public.activity_logs for delete
to authenticated
using (true);

-- Force PostgREST schema cache reload (Supabase)
notify pgrst, 'reload schema';

