-- Material Movement Tracking (Inward & Outward)
-- Track all material movements with costs for dynamic project costing

create table if not exists public.material_movements (
  movement_id bigint generated by default as identity primary key,
  movement_type text not null check (movement_type in ('Inward', 'Outward')),
  sub_type text not null check (sub_type in ('Purchase', 'Purchase Return', 'Issue', 'Utilization', 'Excess Return', 'Adjustment')),
  material_id bigint references public.material_master(material_id) on delete restrict not null,
  project_id bigint references public.projects(project_id) on delete cascade,
  quantity numeric(12,3) not null,
  unit_cost numeric(12,2),
  total_cost numeric(12,2) generated always as (quantity * unit_cost) stored,
  movement_date date default current_date not null,
  reference_type text check (reference_type in ('Allocation', 'Purchase Order', 'Manual', 'Excess Return')),
  reference_id bigint,
  supplier_name text,
  invoice_number text,
  notes text,
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Indexes for performance
create index if not exists idx_material_movements_material on public.material_movements(material_id);
create index if not exists idx_material_movements_project on public.material_movements(project_id);
create index if not exists idx_material_movements_type on public.material_movements(movement_type);
create index if not exists idx_material_movements_date on public.material_movements(movement_date);

-- Function to auto-create movement when stock allocation is issued
create or replace function public.create_movement_on_issue()
returns trigger
language plpgsql
as $$
declare
  v_unit_cost numeric(12,2);
begin
  -- Only create movement if newly issued (not partial update)
  if new.status in ('Issued', 'Partially Issued') and 
     new.issued_quantity > coalesce(old.issued_quantity, 0) then
    
    -- Get average cost of material
    select coalesce(avg(unit_cost), 0) into v_unit_cost
    from public.material_movements
    where material_id = new.material_id
      and movement_type = 'Inward'
      and unit_cost is not null
    limit 100;
    
    -- Create outward movement
    insert into public.material_movements (
      movement_type,
      sub_type,
      material_id,
      project_id,
      quantity,
      unit_cost,
      movement_date,
      reference_type,
      reference_id,
      notes,
      created_by
    ) values (
      'Outward',
      'Issue',
      new.material_id,
      new.project_id,
      new.issued_quantity - coalesce(old.issued_quantity, 0),
      v_unit_cost,
      current_date,
      'Allocation',
      new.allocation_id,
      'Auto-created from stock allocation',
      new.issued_by
    );
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_create_movement_on_issue on public.material_allocations;
create trigger trg_create_movement_on_issue
after update on public.material_allocations
for each row execute function public.create_movement_on_issue();

-- Function to auto-create movement when excess material is returned
create or replace function public.create_movement_on_excess_return()
returns trigger
language plpgsql
as $$
declare
  v_unit_cost numeric(12,2);
begin
  if new.status = 'Available' and old.excess_id is null then
    -- Get average cost of material
    select coalesce(avg(unit_cost), 0) into v_unit_cost
    from public.material_movements
    where material_id = new.material_id
      and movement_type = 'Inward'
      and unit_cost is not null
    limit 100;
    
    -- Create inward movement for return
    insert into public.material_movements (
      movement_type,
      sub_type,
      material_id,
      project_id,
      quantity,
      unit_cost,
      movement_date,
      reference_type,
      reference_id,
      notes,
      created_by
    ) values (
      'Inward',
      'Excess Return',
      new.material_id,
      new.source_project_id,
      new.quantity,
      v_unit_cost,
      new.return_date,
      'Excess Return',
      new.excess_id,
      'Auto-created from excess material return',
      new.returned_by
    );
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_create_movement_on_excess on public.excess_materials;
create trigger trg_create_movement_on_excess
after insert on public.excess_materials
for each row execute function public.create_movement_on_excess_return();

-- RLS policies
alter table public.material_movements enable row level security;

drop policy if exists "material_movements_select_auth" on public.material_movements;
create policy "material_movements_select_auth"
on public.material_movements for select
to authenticated
using (true);

drop policy if exists "material_movements_insert_auth" on public.material_movements;
create policy "material_movements_insert_auth"
on public.material_movements for insert
to authenticated
with check (true);

drop policy if exists "material_movements_update_auth" on public.material_movements;
create policy "material_movements_update_auth"
on public.material_movements for update
to authenticated
using (true)
with check (true);

drop policy if exists "material_movements_delete_auth" on public.material_movements;
create policy "material_movements_delete_auth"
on public.material_movements for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
