-- Dynamic Project Costing with Real-Time Variance
-- Auto-calculate project costs based on material movements

create table if not exists public.project_cost_ledger (
  ledger_id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  cost_category text not null check (cost_category in ('Material', 'Labor', 'Equipment', 'Overhead', 'Other')),
  cost_type text not null check (cost_type in ('Budgeted', 'Actual', 'Variance')),
  amount numeric(12,2) not null,
  description text,
  reference_type text,
  reference_id bigint,
  cost_date date default current_date not null,
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Indexes
create index if not exists idx_project_cost_ledger_project on public.project_cost_ledger(project_id);
create index if not exists idx_project_cost_ledger_category on public.project_cost_ledger(cost_category);
create index if not exists idx_project_cost_ledger_type on public.project_cost_ledger(cost_type);
create index if not exists idx_project_cost_ledger_date on public.project_cost_ledger(cost_date);

-- View for project costing summary with real-time calculations
create or replace view public.project_costing_summary as
select 
  p.project_id,
  p.project_name,
  
  -- Material Costs from Movements
  coalesce(sum(case when mm.movement_type = 'Outward' then mm.total_cost else 0 end), 0) as material_cost_actual,
  
  -- Labor Costs from Payroll
  coalesce((
    select sum(
      case 
        when pe.pay_type = 'Monthly' then coalesce(pe.monthly_salary, 0)
        when pe.pay_type = 'Daily' then coalesce(pe.daily_rate, 0) * coalesce(pe.days_worked, 0)
        else 0
      end + coalesce(pe.incentive, 0) + coalesce(pe.exception_amount, 0)
    )
    from public.payroll_entries pe
    join public.project_manpower pm on pm.team_member_id = pe.user_id
    where pm.project_id = p.project_id
      and pm.labor_type = 'In-House'
  ), 0) as labor_cost_inhouse,
  
  -- Outsourced Labor Costs from Payments
  coalesce((
    select sum(op.amount)
    from public.outsourced_payments op
    where op.project_id = p.project_id
      and op.status in ('Approved', 'Paid')
  ), 0) as labor_cost_outsourced,
  
  -- Budgeted Costs from Ledger
  coalesce((
    select sum(amount)
    from public.project_cost_ledger pcl
    where pcl.project_id = p.project_id
      and pcl.cost_type = 'Budgeted'
  ), 0) as budgeted_total,
  
  -- Financial Transactions (Debit = Expense, Credit = Income)
  coalesce((
    select sum(amount)
    from public.transactions t
    where t.project_id = p.project_id
      and t.type = 'Debit'
  ), 0) as expenses_total,
  
  coalesce((
    select sum(amount)
    from public.transactions t
    where t.project_id = p.project_id
      and t.type = 'Credit'
  ), 0) as income_total,
  
  -- Calculate total actual costs
  coalesce(sum(case when mm.movement_type = 'Outward' then mm.total_cost else 0 end), 0) +
  coalesce((
    select sum(
      case 
        when pe.pay_type = 'Monthly' then coalesce(pe.monthly_salary, 0)
        when pe.pay_type = 'Daily' then coalesce(pe.daily_rate, 0) * coalesce(pe.days_worked, 0)
        else 0
      end + coalesce(pe.incentive, 0) + coalesce(pe.exception_amount, 0)
    )
    from public.payroll_entries pe
    join public.project_manpower pm on pm.team_member_id = pe.user_id
    where pm.project_id = p.project_id
      and pm.labor_type = 'In-House'
  ), 0) +
  coalesce((
    select sum(op.amount)
    from public.outsourced_payments op
    where op.project_id = p.project_id
      and op.status in ('Approved', 'Paid')
  ), 0) as total_actual_cost,
  
  -- Real-time Variance
  coalesce((
    select sum(amount)
    from public.project_cost_ledger pcl
    where pcl.project_id = p.project_id
      and pcl.cost_type = 'Budgeted'
  ), 0) - (
    coalesce(sum(case when mm.movement_type = 'Outward' then mm.total_cost else 0 end), 0) +
    coalesce((
      select sum(
        case 
          when pe.pay_type = 'Monthly' then coalesce(pe.monthly_salary, 0)
          when pe.pay_type = 'Daily' then coalesce(pe.daily_rate, 0) * coalesce(pe.days_worked, 0)
          else 0
        end + coalesce(pe.incentive, 0) + coalesce(pe.exception_amount, 0)
      )
      from public.payroll_entries pe
      join public.project_manpower pm on pm.team_member_id = pe.user_id
      where pm.project_id = p.project_id
        and pm.labor_type = 'In-House'
    ), 0) +
    coalesce((
      select sum(op.amount)
      from public.outsourced_payments op
      where op.project_id = p.project_id
        and op.status in ('Approved', 'Paid')
    ), 0)
  ) as cost_variance,
  
  -- Profit/Loss (Income - Costs)
  coalesce((
    select sum(amount)
    from public.transactions t
    where t.project_id = p.project_id
      and t.type = 'Credit'
  ), 0) - (
    coalesce(sum(case when mm.movement_type = 'Outward' then mm.total_cost else 0 end), 0) +
    coalesce((
      select sum(
        case 
          when pe.pay_type = 'Monthly' then coalesce(pe.monthly_salary, 0)
          when pe.pay_type = 'Daily' then coalesce(pe.daily_rate, 0) * coalesce(pe.days_worked, 0)
          else 0
        end + coalesce(pe.incentive, 0) + coalesce(pe.exception_amount, 0)
      )
      from public.payroll_entries pe
      join public.project_manpower pm on pm.team_member_id = pe.user_id
      where pm.project_id = p.project_id
        and pm.labor_type = 'In-House'
    ), 0) +
    coalesce((
      select sum(op.amount)
      from public.outsourced_payments op
      where op.project_id = p.project_id
        and op.status in ('Approved', 'Paid')
    ), 0)
  ) as profit_loss

from public.projects p
left join public.material_movements mm on mm.project_id = p.project_id
group by p.project_id, p.project_name;

-- Grant access to view
grant select on public.project_costing_summary to authenticated;

-- RLS for cost ledger
alter table public.project_cost_ledger enable row level security;

drop policy if exists "project_cost_ledger_select_auth" on public.project_cost_ledger;
create policy "project_cost_ledger_select_auth"
on public.project_cost_ledger for select
to authenticated
using (true);

drop policy if exists "project_cost_ledger_insert_auth" on public.project_cost_ledger;
create policy "project_cost_ledger_insert_auth"
on public.project_cost_ledger for insert
to authenticated
with check (true);

drop policy if exists "project_cost_ledger_update_auth" on public.project_cost_ledger;
create policy "project_cost_ledger_update_auth"
on public.project_cost_ledger for update
to authenticated
using (true)
with check (true);

drop policy if exists "project_cost_ledger_delete_auth" on public.project_cost_ledger;
create policy "project_cost_ledger_delete_auth"
on public.project_cost_ledger for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
