-- Leads Management Module
-- Track potential projects from leads to orders

create table if not exists public.leads (
  lead_id bigint generated by default as identity primary key,
  lead_number text unique,
  client_name text not null,
  client_email text,
  client_phone text,
  client_address text,
  project_type text,
  estimated_value numeric(12,2),
  estimated_duration_days int,
  source text check (source in ('Referral', 'Website', 'Cold Call', 'Social Media', 'Advertisement', 'Walk-in', 'Other')),
  status text default 'New' not null check (status in ('New', 'Contacted', 'Qualified', 'Proposal Sent', 'Negotiation', 'Won', 'Lost', 'On Hold')),
  priority text default 'Medium' not null check (priority in ('Low', 'Medium', 'High', 'Urgent')),
  description text,
  requirements text,
  notes text,
  assigned_to uuid references auth.users(id),
  contacted_date date,
  follow_up_date date,
  converted_to_order_id bigint references public.project_orders(id),
  converted_at timestamp with time zone,
  lost_reason text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Auto-generate lead number
create or replace function public.generate_lead_number()
returns trigger
language plpgsql
as $$
begin
  if new.lead_number is null then
    new.lead_number := 'LEAD-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(new.lead_id::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_generate_lead_number on public.leads;
create trigger trg_generate_lead_number
before insert on public.leads
for each row execute function public.generate_lead_number();

-- Updated at trigger
drop trigger if exists trg_leads_updated_at on public.leads;
create trigger trg_leads_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

-- Indexes
create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_priority on public.leads(priority);
create index if not exists idx_leads_assigned_to on public.leads(assigned_to);
create index if not exists idx_leads_follow_up_date on public.leads(follow_up_date);
create index if not exists idx_leads_converted_order on public.leads(converted_to_order_id);

-- RLS policies
alter table public.leads enable row level security;

drop policy if exists "leads_select_auth" on public.leads;
create policy "leads_select_auth"
on public.leads for select
to authenticated
using (true);

drop policy if exists "leads_insert_auth" on public.leads;
create policy "leads_insert_auth"
on public.leads for insert
to authenticated
with check (true);

drop policy if exists "leads_update_auth" on public.leads;
create policy "leads_update_auth"
on public.leads for update
to authenticated
using (true)
with check (true);

drop policy if exists "leads_delete_auth" on public.leads;
create policy "leads_delete_auth"
on public.leads for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
