-- ============================================================
-- RBAC: project_members + role-based RLS on projects table
-- Roles: Admin (full access), SiteSupervisor (assigned projects
--        only), Client (assigned projects read-only)
-- ============================================================

-- 1. project_members: links users to specific projects
create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text not null check (role in ('SiteSupervisor', 'Client')),
  assigned_at timestamp with time zone default now() not null,
  assigned_by uuid references auth.users(id),
  constraint project_members_unique unique (project_id, user_id)
);

create index if not exists idx_project_members_project on public.project_members(project_id);
create index if not exists idx_project_members_user on public.project_members(user_id);

-- RLS on project_members
alter table public.project_members enable row level security;

-- Admin: full access
drop policy if exists "project_members_admin_all" on public.project_members;
create policy "project_members_admin_all"
on public.project_members for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'Admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'Admin'
  )
);

-- SiteSupervisor/Client: can see their own memberships
drop policy if exists "project_members_self_select" on public.project_members;
create policy "project_members_self_select"
on public.project_members for select
to authenticated
using (user_id = auth.uid());

-- 2. Update RLS on projects table
-- Drop existing overly-broad policies first
drop policy if exists "projects_select_auth" on public.projects;
drop policy if exists "projects_insert_auth" on public.projects;
drop policy if exists "projects_update_auth" on public.projects;
drop policy if exists "projects_delete_auth" on public.projects;
drop policy if exists "projects_all_auth" on public.projects;

-- Admin: full access to all projects
drop policy if exists "projects_admin_all" on public.projects;
create policy "projects_admin_all"
on public.projects for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'Admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'Admin'
  )
);

-- SiteSupervisor: read + write (update only) for assigned projects
drop policy if exists "projects_supervisor_select" on public.projects;
create policy "projects_supervisor_select"
on public.projects for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = 'SiteSupervisor'
  )
  and exists (
    select 1 from public.project_members pm
    where pm.project_id = projects.project_id and pm.user_id = auth.uid()
  )
);

drop policy if exists "projects_supervisor_update" on public.projects;
create policy "projects_supervisor_update"
on public.projects for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = 'SiteSupervisor'
  )
  and exists (
    select 1 from public.project_members pm
    where pm.project_id = projects.project_id and pm.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = 'SiteSupervisor'
  )
  and exists (
    select 1 from public.project_members pm
    where pm.project_id = projects.project_id and pm.user_id = auth.uid()
  )
);

-- Client: read-only for assigned projects
drop policy if exists "projects_client_select" on public.projects;
create policy "projects_client_select"
on public.projects for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = 'Client'
  )
  and exists (
    select 1 from public.project_members pm
    where pm.project_id = projects.project_id and pm.user_id = auth.uid()
  )
);

-- ProjectManager: same as Admin for backward compat
drop policy if exists "projects_pm_all" on public.projects;
create policy "projects_pm_all"
on public.projects for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'ProjectManager'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'ProjectManager'
  )
);

notify pgrst, 'reload schema';
