-- Project manpower + checklists modules

create table if not exists public.project_manpower (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  role text not null,
  headcount int default 1 not null,
  start_date date,
  end_date date,
  rate_per_day numeric(12,2),
  notes text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

create table if not exists public.project_checklist_items (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  title text not null,
  description text,
  status text default 'Pending' not null,
  due_date date,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Status constraint (idempotent-ish)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'project_checklist_items_status_check'
  ) then
    alter table public.project_checklist_items
      add constraint project_checklist_items_status_check
      check (status in ('Pending', 'In Progress', 'Done'));
  end if;
end $$;

-- Basic updated_at trigger function (shared)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_project_manpower_updated_at on public.project_manpower;
create trigger trg_project_manpower_updated_at
before update on public.project_manpower
for each row execute function public.set_updated_at();

drop trigger if exists trg_project_checklist_items_updated_at on public.project_checklist_items;
create trigger trg_project_checklist_items_updated_at
before update on public.project_checklist_items
for each row execute function public.set_updated_at();

-- RLS
alter table if exists public.project_manpower enable row level security;
alter table if exists public.project_checklist_items enable row level security;

-- Policies
drop policy if exists "project_manpower_select_auth" on public.project_manpower;
drop policy if exists "project_manpower_insert_auth" on public.project_manpower;
drop policy if exists "project_manpower_update_auth" on public.project_manpower;
drop policy if exists "project_manpower_delete_auth" on public.project_manpower;

create policy "project_manpower_select_auth"
on public.project_manpower for select
to authenticated
using (true);

create policy "project_manpower_insert_auth"
on public.project_manpower for insert
to authenticated
with check (true);

create policy "project_manpower_update_auth"
on public.project_manpower for update
to authenticated
using (true)
with check (true);

create policy "project_manpower_delete_auth"
on public.project_manpower for delete
to authenticated
using (true);

drop policy if exists "project_checklist_items_select_auth" on public.project_checklist_items;
drop policy if exists "project_checklist_items_insert_auth" on public.project_checklist_items;
drop policy if exists "project_checklist_items_update_auth" on public.project_checklist_items;
drop policy if exists "project_checklist_items_delete_auth" on public.project_checklist_items;

create policy "project_checklist_items_select_auth"
on public.project_checklist_items for select
to authenticated
using (true);

create policy "project_checklist_items_insert_auth"
on public.project_checklist_items for insert
to authenticated
with check (true);

create policy "project_checklist_items_update_auth"
on public.project_checklist_items for update
to authenticated
using (true)
with check (true);

create policy "project_checklist_items_delete_auth"
on public.project_checklist_items for delete
to authenticated
using (true);

notify pgrst, 'reload schema';

