-- Quotes: line items + sharing/public view fields

create table if not exists public.project_quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint references public.project_quotes(id) on delete cascade not null,
  line_no int not null default 1,
  scope text not null, -- description/scope of work
  metric text, -- e.g. Sq. Ft / Lumpsum
  quantity numeric(15,3),
  unit_price numeric(15,2),
  amount numeric(15,2), -- can be computed client-side; allow direct for lumpsum
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_project_quote_items_quote_id on public.project_quote_items (quote_id);

drop trigger if exists trg_project_quote_items_updated_at on public.project_quote_items;
create trigger trg_project_quote_items_updated_at
before update on public.project_quote_items
for each row execute function public.set_updated_at();

-- Add header fields (idempotent)
alter table if exists public.project_quotes
  add column if not exists customer_name text,
  add column if not exists customer_address text,
  add column if not exists subject text,
  add column if not exists gst_percent numeric(5,2) default 18,
  add column if not exists sub_total numeric(15,2) default 0,
  add column if not exists gst_amount numeric(15,2) default 0,
  add column if not exists grand_total numeric(15,2) default 0,
  add column if not exists terms text,
  add column if not exists share_token text,
  add column if not exists share_enabled boolean default false;

-- Share token uniqueness (idempotent-ish)
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'project_quotes_share_token_unique') then
    alter table public.project_quotes
      add constraint project_quotes_share_token_unique unique (share_token);
  end if;
exception when others then
  -- ignore (e.g., constraint already exists under different name)
end $$;

-- RLS
alter table if exists public.project_quote_items enable row level security;

drop policy if exists "project_quote_items_read_authenticated" on public.project_quote_items;
drop policy if exists "project_quote_items_write_authenticated" on public.project_quote_items;
drop policy if exists "project_quote_items_update_authenticated" on public.project_quote_items;
drop policy if exists "project_quote_items_delete_authenticated" on public.project_quote_items;

create policy "project_quote_items_read_authenticated"
on public.project_quote_items for select
to authenticated
using (true);

create policy "project_quote_items_write_authenticated"
on public.project_quote_items for insert
to authenticated
with check (true);

create policy "project_quote_items_update_authenticated"
on public.project_quote_items for update
to authenticated
using (true)
with check (true);

create policy "project_quote_items_delete_authenticated"
on public.project_quote_items for delete
to authenticated
using (true);

notify pgrst, 'reload schema';

