-- Add missing columns to project_manpower table
alter table public.project_manpower
  add column if not exists labor_type text not null default 'In-House'
    check (labor_type in ('In-House', 'Outsourced')),
  add column if not exists vendor_name text,
  add column if not exists contract_number text,
  add column if not exists contract_amount numeric(14,2),
  add column if not exists team_member_id uuid references auth.users(id) on delete set null;

-- Create outsourced_payments table
create table if not exists public.outsourced_payments (
  payment_id bigint generated by default as identity primary key,
  manpower_id bigint references public.project_manpower(id) on delete cascade not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  payment_type text not null check (payment_type in ('Advance', 'Partial', 'Settlement')),
  payment_date date not null,
  amount numeric(14,2) not null check (amount > 0),
  payment_method text,
  reference_number text,
  status text not null default 'Pending'
    check (status in ('Pending', 'Approved', 'Paid', 'Rejected')),
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create index if not exists idx_outsourced_payments_manpower on public.outsourced_payments(manpower_id);
create index if not exists idx_outsourced_payments_project on public.outsourced_payments(project_id);

-- updated_at trigger for outsourced_payments
drop trigger if exists trg_outsourced_payments_updated_at on public.outsourced_payments;
create trigger trg_outsourced_payments_updated_at
before update on public.outsourced_payments
for each row execute function public.set_updated_at();

-- RLS for outsourced_payments
alter table public.outsourced_payments enable row level security;

drop policy if exists "outsourced_payments_select_auth" on public.outsourced_payments;
create policy "outsourced_payments_select_auth"
on public.outsourced_payments for select to authenticated using (true);

drop policy if exists "outsourced_payments_insert_auth" on public.outsourced_payments;
create policy "outsourced_payments_insert_auth"
on public.outsourced_payments for insert to authenticated with check (true);

drop policy if exists "outsourced_payments_update_auth" on public.outsourced_payments;
create policy "outsourced_payments_update_auth"
on public.outsourced_payments for update to authenticated using (true) with check (true);

drop policy if exists "outsourced_payments_delete_auth" on public.outsourced_payments;
create policy "outsourced_payments_delete_auth"
on public.outsourced_payments for delete to authenticated using (true);

notify pgrst, 'reload schema';
