-- Global Store Inventory System
-- Material master with dynamic quantities, material requests with approval, returns workflow

-- Drop old material_master if exists and create new structure
drop table if exists public.material_master cascade;

-- Materials Master (Dynamic list managed by admin)
create table if not exists public.materials_master (
  material_id bigint generated by default as identity primary key,
  material_name text unique not null,
  description text,
  metric text not null check (metric in ('Litres', 'Kgs', 'Tonnes', 'Sqft', 'Metres', 'Units', 'Pieces', 'Boxes', 'Bags')),
  is_active boolean default true,
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Material Quantity Variants (e.g., 20L, 10L, 5L for same material)
create table if not exists public.material_variants (
  variant_id bigint generated by default as identity primary key,
  material_id bigint references public.materials_master(material_id) on delete cascade not null,
  variant_name text not null, -- e.g., "20 Litre Can", "10 Litre Bucket"
  quantity_per_unit numeric(12,3) not null, -- e.g., 20 for 20L can
  is_active boolean default true,
  created_at timestamp with time zone default now() not null
);

-- Store Inventory (Global, Project-independent)
create table if not exists public.store_inventory (
  inventory_id bigint generated by default as identity primary key,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  variant_id bigint references public.material_variants(variant_id) on delete restrict not null,
  number_of_units int not null default 0, -- How many units (cans, bags, etc.)
  total_quantity numeric(12,3) not null default 0, -- Total quantity (e.g., 20L x 5 units = 100L)
  location text,
  notes text,
  last_updated timestamp with time zone default now() not null,
  updated_by uuid references auth.users(id)
);

-- Unique constraint: one row per material-variant combination
create unique index if not exists idx_store_inventory_unique 
on public.store_inventory(material_id, variant_id);

-- Material Requests (from projects)
create table if not exists public.material_requests (
  request_id bigint generated by default as identity primary key,
  request_number text unique not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  
  -- Request details
  requested_quantity numeric(12,3) not null,
  request_source text not null check (request_source in ('Store', 'Local Procurement')),
  priority text default 'Normal' check (priority in ('Urgent', 'High', 'Normal', 'Low')),
  required_by date,
  purpose text,
  
  -- Approval workflow
  status text default 'Pending' not null check (status in ('Pending', 'Approved', 'Rejected', 'Fulfilled', 'Cancelled')),
  approved_by uuid references auth.users(id),
  approved_at timestamp with time zone,
  approval_notes text,
  
  -- Fulfillment tracking
  fulfilled_quantity numeric(12,3),
  fulfilled_at timestamp with time zone,
  fulfillment_notes text,
  
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Material Request Fulfillment Items (which units were used)
create table if not exists public.request_fulfillment_items (
  fulfillment_item_id bigint generated by default as identity primary key,
  request_id bigint references public.material_requests(request_id) on delete cascade not null,
  variant_id bigint references public.material_variants(variant_id) on delete restrict not null,
  units_issued int not null, -- How many units of this variant
  quantity_issued numeric(12,3) not null, -- Total quantity from these units
  issued_at timestamp with time zone default now() not null,
  issued_by uuid references auth.users(id)
);

-- Material Returns (from projects back to store)
create table if not exists public.material_returns (
  return_id bigint generated by default as identity primary key,
  return_number text unique not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  variant_id bigint references public.material_variants(variant_id),
  
  -- Return details
  returned_quantity numeric(12,3) not null,
  number_of_units int,
  condition text check (condition in ('Excellent', 'Good', 'Fair', 'Damaged', 'Unusable')),
  reason text,
  
  -- Store approval workflow
  status text default 'Pending' not null check (status in ('Pending', 'Accepted', 'Rejected')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamp with time zone,
  review_notes text,
  
  -- Original request reference
  source_request_id bigint references public.material_requests(request_id),
  
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Material Movement Logs (Complete audit trail)
create table if not exists public.material_movement_logs (
  log_id bigint generated by default as identity primary key,
  material_id bigint references public.materials_master(material_id) on delete restrict not null,
  variant_id bigint references public.material_variants(variant_id),
  
  -- Movement details
  movement_type text not null check (movement_type in ('Store In', 'Store Out', 'Project In', 'Project Out', 'Return to Store', 'Local Procurement')),
  project_id bigint references public.projects(project_id),
  quantity numeric(12,3) not null,
  number_of_units int,
  
  -- References
  reference_type text check (reference_type in ('Material Request', 'Material Return', 'Manual Adjustment', 'Initial Stock')),
  reference_id bigint,
  
  -- Additional info
  notes text,
  movement_date timestamp with time zone default now() not null,
  created_by uuid references auth.users(id)
);

-- Auto-generate request numbers
create or replace function public.generate_request_number()
returns trigger
language plpgsql
as $$
declare
  v_sequence int;
  v_request_number text;
begin
  select coalesce(max(
    case 
      when request_number ~ '^MR-[0-9]+$' 
      then substring(request_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.material_requests;
  
  v_request_number := 'MR-' || lpad(v_sequence::text, 4, '0');
  new.request_number := v_request_number;
  
  return new;
end;
$$;

drop trigger if exists trg_generate_request_number on public.material_requests;
create trigger trg_generate_request_number
before insert on public.material_requests
for each row 
when (new.request_number is null or new.request_number = '')
execute function public.generate_request_number();

-- Auto-generate return numbers
create or replace function public.generate_return_number()
returns trigger
language plpgsql
as $$
declare
  v_sequence int;
  v_return_number text;
begin
  select coalesce(max(
    case 
      when return_number ~ '^RTN-[0-9]+$' 
      then substring(return_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.material_returns;
  
  v_return_number := 'RTN-' || lpad(v_sequence::text, 4, '0');
  new.return_number := v_return_number;
  
  return new;
end;
$$;

drop trigger if exists trg_generate_return_number on public.material_returns;
create trigger trg_generate_return_number
before insert on public.material_returns
for each row 
when (new.return_number is null or new.return_number = '')
execute function public.generate_return_number();

-- Function: Update store inventory when request fulfilled
create or replace function public.update_store_inventory_on_fulfillment()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'Fulfilled' and old.status != 'Fulfilled' then
    -- Log the movement
    insert into public.material_movement_logs (
      material_id,
      movement_type,
      project_id,
      quantity,
      reference_type,
      reference_id,
      notes,
      created_by
    ) values (
      new.material_id,
      case when new.request_source = 'Store' then 'Store Out' else 'Local Procurement' end,
      new.project_id,
      new.fulfilled_quantity,
      'Material Request',
      new.request_id,
      'Fulfilled request: ' || new.request_number,
      new.approved_by
    );
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_update_inventory_on_fulfillment on public.material_requests;
create trigger trg_update_inventory_on_fulfillment
after update on public.material_requests
for each row execute function public.update_store_inventory_on_fulfillment();

-- Function: Handle material returns to store
create or replace function public.handle_material_return_to_store()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'Accepted' and old.status = 'Pending' then
    -- Add back to store inventory if variant specified
    if new.variant_id is not null then
      insert into public.store_inventory (
        material_id,
        variant_id,
        number_of_units,
        total_quantity,
        notes
      ) values (
        new.material_id,
        new.variant_id,
        coalesce(new.number_of_units, 0),
        new.returned_quantity,
        'Returned from project via ' || new.return_number
      )
      on conflict (material_id, variant_id) 
      do update set
        number_of_units = store_inventory.number_of_units + excluded.number_of_units,
        total_quantity = store_inventory.total_quantity + excluded.total_quantity,
        last_updated = now();
    end if;
    
    -- Log the movement
    insert into public.material_movement_logs (
      material_id,
      variant_id,
      movement_type,
      project_id,
      quantity,
      number_of_units,
      reference_type,
      reference_id,
      notes,
      created_by
    ) values (
      new.material_id,
      new.variant_id,
      'Return to Store',
      new.project_id,
      new.returned_quantity,
      new.number_of_units,
      'Material Return',
      new.return_id,
      'Accepted return: ' || new.return_number,
      new.reviewed_by
    );
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_handle_return_to_store on public.material_returns;
create trigger trg_handle_return_to_store
after update on public.material_returns
for each row execute function public.handle_material_return_to_store();

-- Indexes
create index if not exists idx_materials_master_name on public.materials_master(material_name);
create index if not exists idx_material_variants_material on public.material_variants(material_id);
create index if not exists idx_store_inventory_material on public.store_inventory(material_id);
create index if not exists idx_material_requests_project on public.material_requests(project_id);
create index if not exists idx_material_requests_status on public.material_requests(status);
create index if not exists idx_material_returns_project on public.material_returns(project_id);
create index if not exists idx_material_returns_status on public.material_returns(status);
create index if not exists idx_movement_logs_material on public.material_movement_logs(material_id);
create index if not exists idx_movement_logs_project on public.material_movement_logs(project_id);

-- RLS Policies
alter table public.materials_master enable row level security;
alter table public.material_variants enable row level security;
alter table public.store_inventory enable row level security;
alter table public.material_requests enable row level security;
alter table public.request_fulfillment_items enable row level security;
alter table public.material_returns enable row level security;
alter table public.material_movement_logs enable row level security;

-- Materials Master
drop policy if exists "materials_master_select_auth" on public.materials_master;
create policy "materials_master_select_auth" on public.materials_master for select to authenticated using (true);

drop policy if exists "materials_master_insert_auth" on public.materials_master;
create policy "materials_master_insert_auth" on public.materials_master for insert to authenticated with check (true);

drop policy if exists "materials_master_update_auth" on public.materials_master;
create policy "materials_master_update_auth" on public.materials_master for update to authenticated using (true);

drop policy if exists "materials_master_delete_auth" on public.materials_master;
create policy "materials_master_delete_auth" on public.materials_master for delete to authenticated using (true);

-- Material Variants
drop policy if exists "material_variants_select_auth" on public.material_variants;
create policy "material_variants_select_auth" on public.material_variants for select to authenticated using (true);

drop policy if exists "material_variants_insert_auth" on public.material_variants;
create policy "material_variants_insert_auth" on public.material_variants for insert to authenticated with check (true);

drop policy if exists "material_variants_update_auth" on public.material_variants;
create policy "material_variants_update_auth" on public.material_variants for update to authenticated using (true);

drop policy if exists "material_variants_delete_auth" on public.material_variants;
create policy "material_variants_delete_auth" on public.material_variants for delete to authenticated using (true);

-- Store Inventory
drop policy if exists "store_inventory_select_auth" on public.store_inventory;
create policy "store_inventory_select_auth" on public.store_inventory for select to authenticated using (true);

drop policy if exists "store_inventory_insert_auth" on public.store_inventory;
create policy "store_inventory_insert_auth" on public.store_inventory for insert to authenticated with check (true);

drop policy if exists "store_inventory_update_auth" on public.store_inventory;
create policy "store_inventory_update_auth" on public.store_inventory for update to authenticated using (true);

drop policy if exists "store_inventory_delete_auth" on public.store_inventory;
create policy "store_inventory_delete_auth" on public.store_inventory for delete to authenticated using (true);

-- Material Requests (all policies)
drop policy if exists "material_requests_select_auth" on public.material_requests;
create policy "material_requests_select_auth" on public.material_requests for select to authenticated using (true);

drop policy if exists "material_requests_insert_auth" on public.material_requests;
create policy "material_requests_insert_auth" on public.material_requests for insert to authenticated with check (true);

drop policy if exists "material_requests_update_auth" on public.material_requests;
create policy "material_requests_update_auth" on public.material_requests for update to authenticated using (true);

drop policy if exists "material_requests_delete_auth" on public.material_requests;
create policy "material_requests_delete_auth" on public.material_requests for delete to authenticated using (true);

-- Request Fulfillment Items
drop policy if exists "request_fulfillment_items_select_auth" on public.request_fulfillment_items;
create policy "request_fulfillment_items_select_auth" on public.request_fulfillment_items for select to authenticated using (true);

drop policy if exists "request_fulfillment_items_insert_auth" on public.request_fulfillment_items;
create policy "request_fulfillment_items_insert_auth" on public.request_fulfillment_items for insert to authenticated with check (true);

-- Material Returns (all policies)
drop policy if exists "material_returns_select_auth" on public.material_returns;
create policy "material_returns_select_auth" on public.material_returns for select to authenticated using (true);

drop policy if exists "material_returns_insert_auth" on public.material_returns;
create policy "material_returns_insert_auth" on public.material_returns for insert to authenticated with check (true);

drop policy if exists "material_returns_update_auth" on public.material_returns;
create policy "material_returns_update_auth" on public.material_returns for update to authenticated using (true);

drop policy if exists "material_returns_delete_auth" on public.material_returns;
create policy "material_returns_delete_auth" on public.material_returns for delete to authenticated using (true);

-- Movement Logs
drop policy if exists "material_movement_logs_select_auth" on public.material_movement_logs;
create policy "material_movement_logs_select_auth" on public.material_movement_logs for select to authenticated using (true);

drop policy if exists "material_movement_logs_insert_auth" on public.material_movement_logs;
create policy "material_movement_logs_insert_auth" on public.material_movement_logs for insert to authenticated with check (true);

notify pgrst, 'reload schema';
