-- Ensure project_tasks matches web app expectations and common legacy variants (idempotent)
-- Fixes insert failures due to missing columns / NOT NULL legacy columns.

-- Create table if missing (minimal)
create table if not exists public.project_tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  title text not null,
  description text,
  status text default 'Todo' not null,
  priority text default 'Medium' not null,
  due_date date,
  assignee_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

-- Add missing columns (including common legacy names)
alter table if exists public.project_tasks add column if not exists project_id bigint;
alter table if exists public.project_tasks add column if not exists title text;
alter table if exists public.project_tasks add column if not exists description text;
alter table if exists public.project_tasks add column if not exists status text;
alter table if exists public.project_tasks add column if not exists priority text;
alter table if exists public.project_tasks add column if not exists due_date date;
alter table if exists public.project_tasks add column if not exists assignee_name text;
alter table if exists public.project_tasks add column if not exists created_at timestamp with time zone;
alter table if exists public.project_tasks add column if not exists updated_at timestamp with time zone;
alter table if exists public.project_tasks add column if not exists created_by uuid references auth.users(id);

-- Compatibility columns (some schemas use these)
alter table if exists public.project_tasks add column if not exists content text;
alter table if exists public.project_tasks add column if not exists name text;
alter table if exists public.project_tasks add column if not exists task_name text;

-- Backfill timestamps + defaults if missing
update public.project_tasks
  set created_at = timezone('utc'::text, now())
  where created_at is null;

update public.project_tasks
  set updated_at = timezone('utc'::text, now())
  where updated_at is null;

alter table if exists public.project_tasks
  alter column created_at set default timezone('utc'::text, now());

alter table if exists public.project_tasks
  alter column updated_at set default timezone('utc'::text, now());

-- Best-effort content/name backfill
update public.project_tasks
  set name = coalesce(name, title, task_name)
  where name is null;

update public.project_tasks
  set task_name = coalesce(task_name, title, name)
  where task_name is null;

update public.project_tasks
  set content = coalesce(content, description, title, '')
  where content is null;

-- Enable RLS + policies
alter table if exists public.project_tasks enable row level security;

drop policy if exists "project_tasks_read_authenticated" on public.project_tasks;
drop policy if exists "project_tasks_write_authenticated" on public.project_tasks;
drop policy if exists "project_tasks_update_authenticated" on public.project_tasks;
drop policy if exists "project_tasks_delete_authenticated" on public.project_tasks;

create policy "project_tasks_read_authenticated"
on public.project_tasks for select
to authenticated
using (true);

create policy "project_tasks_write_authenticated"
on public.project_tasks for insert
to authenticated
with check (true);

create policy "project_tasks_update_authenticated"
on public.project_tasks for update
to authenticated
using (true);

create policy "project_tasks_delete_authenticated"
on public.project_tasks for delete
to authenticated
using (true);

-- Reload PostgREST schema cache
notify pgrst, 'reload schema';

