-- Payslips / Payroll entries
-- Supports:
-- 1) Fixed Monthly Salary + Incentive(optional)
-- 2) Daily labour: Daily rate(default) + days worked + exception amount(optional) + incentive(optional)

create table if not exists public.payroll_entries (
  payroll_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(user_id) on delete cascade not null,
  pay_month date not null, -- store as first day of month (YYYY-MM-01)
  pay_type text not null, -- 'Monthly' | 'Daily'

  -- Monthly fields
  monthly_salary numeric(12,2),

  -- Daily fields
  daily_rate numeric(12,2),
  days_worked int,

  -- Common
  incentive numeric(12,2) not null default 0,
  exception_amount numeric(12,2) not null default 0,
  notes text,

  status text not null default 'Draft', -- Draft | Paid
  paid_at timestamp with time zone,

  created_by uuid references auth.users(id),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- One payslip per person per month
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'payroll_entries_user_month_unique') then
    alter table public.payroll_entries
      add constraint payroll_entries_user_month_unique unique (user_id, pay_month);
  end if;
end $$;

-- Enforce pay_month is first of month
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'payroll_entries_pay_month_first_day_check') then
    alter table public.payroll_entries
      add constraint payroll_entries_pay_month_first_day_check
      check (pay_month = (date_trunc('month', pay_month::timestamp))::date);
  end if;
end $$;

-- Enforce pay_type values
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'payroll_entries_pay_type_check') then
    alter table public.payroll_entries
      add constraint payroll_entries_pay_type_check
      check (pay_type in ('Monthly', 'Daily'));
  end if;
end $$;

-- Enforce status values
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'payroll_entries_status_check') then
    alter table public.payroll_entries
      add constraint payroll_entries_status_check
      check (status in ('Draft', 'Paid'));
  end if;
end $$;

-- Enforce required fields per pay_type
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'payroll_entries_type_fields_check') then
    alter table public.payroll_entries
      add constraint payroll_entries_type_fields_check
      check (
        (pay_type = 'Monthly' and monthly_salary is not null and daily_rate is null and days_worked is null)
        or
        (pay_type = 'Daily' and daily_rate is not null and days_worked is not null and monthly_salary is null)
      );
  end if;
end $$;

create index if not exists idx_payroll_entries_user_month
  on public.payroll_entries (user_id, pay_month desc);

drop trigger if exists trg_payroll_entries_updated_at on public.payroll_entries;
create trigger trg_payroll_entries_updated_at
before update on public.payroll_entries
for each row execute function public.set_updated_at();

-- RLS: employees can read their own payslips; writes via service role API
alter table if exists public.payroll_entries enable row level security;

drop policy if exists "payroll_entries_select_own" on public.payroll_entries;
create policy "payroll_entries_select_own"
on public.payroll_entries for select
to authenticated
using (auth.uid() = user_id);

notify pgrst, 'reload schema';

