-- Lead & Conversion Workflow with Dynamic Estimating
-- Persistent data capture, revisable estimates, automated conversion

-- Update leads table with enhanced status tracking
alter table public.leads
drop constraint if exists leads_status_check;

alter table public.leads
add constraint leads_status_check check (status in (
  'New', 
  'Contacted', 
  'In Progress',
  'Qualified', 
  'Proposal Sent', 
  'Negotiation', 
  'Realized',
  'Unrealized',
  'Won', 
  'Lost'
));

-- Add persistent data capture flag (auto-save everything)
alter table public.leads
add column if not exists data_captured_at timestamp with time zone,
add column if not exists last_activity_at timestamp with time zone default now();

-- Update trigger to mark data as captured immediately
create or replace function public.auto_capture_lead_data()
returns trigger
language plpgsql
as $$
begin
  if new.data_captured_at is null then
    new.data_captured_at := now();
  end if;
  new.last_activity_at := now();
  return new;
end;
$$;

drop trigger if exists trg_auto_capture_lead_data on public.leads;
create trigger trg_auto_capture_lead_data
before insert or update on public.leads
for each row execute function public.auto_capture_lead_data();

-- Estimates Table (Dynamic, Revisable)
create table if not exists public.estimates (
  estimate_id bigint generated by default as identity primary key,
  estimate_number text unique not null,
  lead_id bigint references public.leads(lead_id) on delete cascade not null,
  
  -- Estimate Details
  estimate_name text not null,
  revision_number int default 1 not null,
  status text default 'Draft' check (status in ('Draft', 'Under Review', 'Sent to Client', 'Approved', 'Rejected', 'Revised')) not null,
  
  -- Pricing
  subtotal numeric(15,2) default 0,
  tax_percentage numeric(5,2) default 0,
  tax_amount numeric(15,2) default 0,
  discount_percentage numeric(5,2) default 0,
  discount_amount numeric(15,2) default 0,
  total_amount numeric(15,2) default 0,
  
  -- Dates
  estimate_date date default current_date not null,
  valid_until date,
  approved_date date,
  
  -- Notes
  terms_and_conditions text,
  internal_notes text,
  client_notes text,
  
  -- Approval workflow
  approved_by uuid references auth.users(id),
  approval_notes text,
  
  -- Metadata
  created_at timestamp with time zone default now() not null,
  created_by uuid references auth.users(id),
  updated_at timestamp with time zone default now() not null,
  is_active boolean default true
);

-- Estimate Line Items
create table if not exists public.estimate_items (
  item_id bigint generated by default as identity primary key,
  estimate_id bigint references public.estimates(estimate_id) on delete cascade not null,
  
  -- Item Details
  item_number int not null,
  description text not null,
  category text,
  quantity numeric(12,3) not null,
  unit text,
  
  -- Pricing
  unit_price numeric(12,2) not null,
  line_total numeric(15,2) generated always as (quantity * unit_price) stored,
  
  -- Material linking (optional)
  material_id bigint references public.material_master(material_id),
  
  -- Notes
  notes text,
  
  created_at timestamp with time zone default now() not null
);

-- Function: Auto-generate estimate number
create or replace function public.generate_estimate_number()
returns trigger
language plpgsql
as $$
declare
  v_year text;
  v_month text;
  v_sequence int;
  v_estimate_number text;
begin
  v_year := to_char(current_date, 'YYYY');
  v_month := to_char(current_date, 'MM');
  
  -- Get next sequence for this month
  select coalesce(max(
    case 
      when estimate_number ~ ('^EST-' || v_year || v_month || '-[0-9]+$')
      then substring(estimate_number from '[0-9]+$')::int
      else 0
    end
  ), 0) + 1
  into v_sequence
  from public.estimates;
  
  v_estimate_number := 'EST-' || v_year || v_month || '-' || lpad(v_sequence::text, 4, '0');
  new.estimate_number := v_estimate_number;
  
  return new;
end;
$$;

drop trigger if exists trg_generate_estimate_number on public.estimates;
create trigger trg_generate_estimate_number
before insert on public.estimates
for each row 
when (new.estimate_number is null or new.estimate_number = '')
execute function public.generate_estimate_number();

-- Function: Update estimate totals
create or replace function public.update_estimate_totals()
returns trigger
language plpgsql
as $$
declare
  v_subtotal numeric(15,2);
  v_tax_amount numeric(15,2);
  v_discount_amount numeric(15,2);
  v_total numeric(15,2);
begin
  -- Calculate subtotal from all items
  select coalesce(sum(line_total), 0)
  into v_subtotal
  from public.estimate_items
  where estimate_id = coalesce(new.estimate_id, old.estimate_id);
  
  -- Get estimate for tax/discount percentages
  select 
    v_subtotal,
    v_subtotal * (tax_percentage / 100),
    v_subtotal * (discount_percentage / 100)
  into v_subtotal, v_tax_amount, v_discount_amount
  from public.estimates
  where estimate_id = coalesce(new.estimate_id, old.estimate_id);
  
  v_total := v_subtotal + v_tax_amount - v_discount_amount;
  
  -- Update estimate
  update public.estimates
  set 
    subtotal = v_subtotal,
    tax_amount = v_tax_amount,
    discount_amount = v_discount_amount,
    total_amount = v_total,
    updated_at = now()
  where estimate_id = coalesce(new.estimate_id, old.estimate_id);
  
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_update_estimate_totals_insert on public.estimate_items;
create trigger trg_update_estimate_totals_insert
after insert or update or delete on public.estimate_items
for each row execute function public.update_estimate_totals();

-- Function: Automated Conversion Trigger (Estimate Approval → Order + Quotation)
create or replace function public.auto_convert_estimate_to_order()
returns trigger
language plpgsql
as $$
declare
  v_lead record;
  v_project_id bigint;
  v_order_id bigint;
  v_quote_id bigint;
begin
  -- Only trigger on approval
  if new.status = 'Approved' and old.status != 'Approved' then
    
    -- Get lead details
    select * into v_lead
    from public.leads
    where lead_id = new.lead_id;
    
    -- Create Project (if not exists)
    insert into public.projects (
      project_name,
      client_id,
      status,
      start_date,
      estimated_value,
      created_at
    )
    values (
      v_lead.project_name,
      null, -- Will be set from client_name
      'Planning',
      current_date,
      new.total_amount,
      now()
    )
    returning project_id into v_project_id;
    
    -- Create Project Order
    insert into public.project_orders (
      order_number,
      project_id,
      client_name,
      client_email,
      client_phone,
      client_address,
      order_date,
      project_type,
      project_duration,
      estimated_value,
      status,
      source,
      notes,
      converted_from_lead_id,
      created_at
    )
    values (
      'ORD-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('project_orders_order_id_seq')::text, 4, '0'),
      v_project_id,
      v_lead.client_name,
      v_lead.email,
      v_lead.phone,
      v_lead.address,
      current_date,
      v_lead.project_type,
      v_lead.estimated_duration,
      new.total_amount,
      'Confirmed',
      'Lead Conversion',
      'Auto-created from approved estimate: ' || new.estimate_number,
      v_lead.lead_id,
      now()
    )
    returning order_id into v_order_id;
    
    -- Create Quotation from Estimate
    insert into public.quotes (
      quote_number,
      project_id,
      client_name,
      client_email,
      quote_date,
      valid_until,
      subtotal,
      tax_percentage,
      tax_amount,
      discount_amount,
      total,
      status,
      notes,
      created_at
    )
    values (
      'QUO-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(nextval('quotes_quote_id_seq')::text, 4, '0'),
      v_project_id,
      v_lead.client_name,
      v_lead.email,
      new.estimate_date,
      new.valid_until,
      new.subtotal,
      new.tax_percentage,
      new.tax_amount,
      new.discount_amount,
      new.total_amount,
      'Accepted',
      'Auto-created from approved estimate: ' || new.estimate_number || '. ' || new.client_notes,
      now()
    )
    returning quote_id into v_quote_id;
    
    -- Copy estimate items to quote items
    insert into public.quote_items (
      quote_id,
      item_number,
      description,
      quantity,
      unit,
      unit_price,
      notes
    )
    select
      v_quote_id,
      item_number,
      description,
      quantity,
      unit,
      unit_price,
      notes
    from public.estimate_items
    where estimate_id = new.estimate_id;
    
    -- Update lead status to Realized/Won
    update public.leads
    set 
      status = 'Realized',
      converted_to_order_id = v_order_id,
      conversion_date = now()
    where lead_id = new.lead_id;
    
    -- Log the conversion
    new.approval_notes := coalesce(new.approval_notes, '') || 
      ' | Auto-converted: Order #' || v_order_id || ', Quote #' || v_quote_id || ', Project #' || v_project_id;
    
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_auto_convert_estimate on public.estimates;
create trigger trg_auto_convert_estimate
before update on public.estimates
for each row execute function public.auto_convert_estimate_to_order();

-- Project Planning Integration: Mandatory fields on conversion
alter table public.projects
add column if not exists schedule_start_date date,
add column if not exists schedule_end_date date,
add column if not exists schedule_notes text,
add column if not exists boq_document_url text,
add column if not exists external_requirements text,
add column if not exists planning_completed boolean default false;

alter table public.project_orders
add column if not exists schedule_start_date date,
add column if not exists schedule_end_date date,
add column if not exists boq_notes text,
add column if not exists external_requirements text;

-- View: Estimates with Lead details
create or replace view public.estimates_with_leads as
select 
  e.*,
  l.client_name,
  l.email as client_email,
  l.phone as client_phone,
  l.project_type,
  l.source as lead_source,
  l.priority,
  l.status as lead_status,
  (select count(*) from public.estimate_items ei where ei.estimate_id = e.estimate_id) as item_count
from public.estimates e
join public.leads l on l.lead_id = e.lead_id;

grant select on public.estimates_with_leads to authenticated;

-- Indexes
create index if not exists idx_estimates_lead on public.estimates(lead_id);
create index if not exists idx_estimates_status on public.estimates(status);
create index if not exists idx_estimates_number on public.estimates(estimate_number);
create index if not exists idx_estimate_items_estimate on public.estimate_items(estimate_id);

-- RLS Policies
alter table public.estimates enable row level security;
alter table public.estimate_items enable row level security;

drop policy if exists "estimates_select_auth" on public.estimates;
create policy "estimates_select_auth"
on public.estimates for select
to authenticated
using (true);

drop policy if exists "estimates_insert_auth" on public.estimates;
create policy "estimates_insert_auth"
on public.estimates for insert
to authenticated
with check (true);

drop policy if exists "estimates_update_auth" on public.estimates;
create policy "estimates_update_auth"
on public.estimates for update
to authenticated
using (true)
with check (true);

drop policy if exists "estimates_delete_auth" on public.estimates;
create policy "estimates_delete_auth"
on public.estimates for delete
to authenticated
using (true);

drop policy if exists "estimate_items_select_auth" on public.estimate_items;
create policy "estimate_items_select_auth"
on public.estimate_items for select
to authenticated
using (true);

drop policy if exists "estimate_items_insert_auth" on public.estimate_items;
create policy "estimate_items_insert_auth"
on public.estimate_items for insert
to authenticated
with check (true);

drop policy if exists "estimate_items_update_auth" on public.estimate_items;
create policy "estimate_items_update_auth"
on public.estimate_items for update
to authenticated
using (true)
with check (true);

drop policy if exists "estimate_items_delete_auth" on public.estimate_items;
create policy "estimate_items_delete_auth"
on public.estimate_items for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
