-- Project Modules: Notes, Tasks, Files, Moodboard, Quotes, Orders, Invoices
-- This migration adds minimal tables to power project-level tabs in the web app.

-- -----------------------------
-- 1) project_notes
-- -----------------------------
create table if not exists public.project_notes (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  title text not null,
  body text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_notes_project_id on public.project_notes (project_id);

alter table public.project_notes enable row level security;

create policy "project_notes_read_authenticated"
on public.project_notes for select
to authenticated
using (true);

create policy "project_notes_write_authenticated"
on public.project_notes for insert
to authenticated
with check (true);

create policy "project_notes_update_authenticated"
on public.project_notes for update
to authenticated
using (true);

create policy "project_notes_delete_authenticated"
on public.project_notes for delete
to authenticated
using (true);

-- -----------------------------
-- 2) project_tasks
-- -----------------------------
create table if not exists public.project_tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  title text not null,
  description text,
  status text default 'Todo' not null, -- Todo | In Progress | Done
  priority text default 'Medium' not null, -- Low | Medium | High
  due_date date,
  assignee_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_tasks_project_id on public.project_tasks (project_id);
create index if not exists idx_project_tasks_status on public.project_tasks (status);

alter table public.project_tasks enable row level security;

create policy "project_tasks_read_authenticated"
on public.project_tasks for select
to authenticated
using (true);

create policy "project_tasks_write_authenticated"
on public.project_tasks for insert
to authenticated
with check (true);

create policy "project_tasks_update_authenticated"
on public.project_tasks for update
to authenticated
using (true);

create policy "project_tasks_delete_authenticated"
on public.project_tasks for delete
to authenticated
using (true);

-- -----------------------------
-- 3) project_files (metadata for storage objects)
-- -----------------------------
create table if not exists public.project_files (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  bucket text not null default 'documents',
  object_path text not null, -- storage object path (within bucket)
  file_name text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_files_project_id on public.project_files (project_id);

alter table public.project_files enable row level security;

create policy "project_files_read_authenticated"
on public.project_files for select
to authenticated
using (true);

create policy "project_files_write_authenticated"
on public.project_files for insert
to authenticated
with check (true);

create policy "project_files_delete_authenticated"
on public.project_files for delete
to authenticated
using (true);

-- -----------------------------
-- 4) project_moodboard_items (image references in storage)
-- -----------------------------
create table if not exists public.project_moodboard_items (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  title text,
  bucket text not null default 'documents',
  image_path text not null, -- storage object path (within bucket)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_moodboard_project_id on public.project_moodboard_items (project_id);

alter table public.project_moodboard_items enable row level security;

create policy "project_moodboard_read_authenticated"
on public.project_moodboard_items for select
to authenticated
using (true);

create policy "project_moodboard_write_authenticated"
on public.project_moodboard_items for insert
to authenticated
with check (true);

create policy "project_moodboard_delete_authenticated"
on public.project_moodboard_items for delete
to authenticated
using (true);

-- -----------------------------
-- 5) project_quotes (header-level; line items can be added later)
-- -----------------------------
create table if not exists public.project_quotes (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  quote_number text,
  vendor_name text,
  title text,
  total_amount numeric(15,2) default 0,
  status text default 'Draft' not null, -- Draft | Sent | Approved | Rejected
  issued_date date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_quotes_project_id on public.project_quotes (project_id);

alter table public.project_quotes enable row level security;

create policy "project_quotes_read_authenticated"
on public.project_quotes for select
to authenticated
using (true);

create policy "project_quotes_write_authenticated"
on public.project_quotes for insert
to authenticated
with check (true);

create policy "project_quotes_update_authenticated"
on public.project_quotes for update
to authenticated
using (true);

create policy "project_quotes_delete_authenticated"
on public.project_quotes for delete
to authenticated
using (true);

-- -----------------------------
-- 6) project_orders (header-level)
-- -----------------------------
create table if not exists public.project_orders (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  order_number text,
  vendor_name text,
  title text,
  total_amount numeric(15,2) default 0,
  status text default 'Draft' not null, -- Draft | Placed | Delivered | Cancelled
  order_date date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_orders_project_id on public.project_orders (project_id);

alter table public.project_orders enable row level security;

create policy "project_orders_read_authenticated"
on public.project_orders for select
to authenticated
using (true);

create policy "project_orders_write_authenticated"
on public.project_orders for insert
to authenticated
with check (true);

create policy "project_orders_update_authenticated"
on public.project_orders for update
to authenticated
using (true);

create policy "project_orders_delete_authenticated"
on public.project_orders for delete
to authenticated
using (true);

-- -----------------------------
-- 7) project_invoices (header-level)
-- -----------------------------
create table if not exists public.project_invoices (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  invoice_number text,
  counterparty_name text, -- client or vendor
  title text,
  total_amount numeric(15,2) default 0,
  status text default 'Draft' not null, -- Draft | Sent | Paid | Overdue | Cancelled
  issued_date date,
  due_date date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

create index if not exists idx_project_invoices_project_id on public.project_invoices (project_id);

alter table public.project_invoices enable row level security;

create policy "project_invoices_read_authenticated"
on public.project_invoices for select
to authenticated
using (true);

create policy "project_invoices_write_authenticated"
on public.project_invoices for insert
to authenticated
with check (true);

create policy "project_invoices_update_authenticated"
on public.project_invoices for update
to authenticated
using (true);

create policy "project_invoices_delete_authenticated"
on public.project_invoices for delete
to authenticated
using (true);

