-- Real-time Stock Allocation Tracking
-- Prevents double-allocation of materials across projects

create table if not exists public.material_allocations (
  allocation_id bigint generated by default as identity primary key,
  material_id bigint references public.material_master(material_id) on delete restrict not null,
  project_id bigint references public.projects(project_id) on delete cascade not null,
  allocated_quantity numeric(12,3) not null check (allocated_quantity > 0),
  allocation_date date default current_date not null,
  required_by_date date,
  status text default 'Reserved' not null check (status in ('Reserved', 'Issued', 'Partially Issued', 'Returned', 'Cancelled')),
  issued_quantity numeric(12,3) default 0 check (issued_quantity >= 0),
  returned_quantity numeric(12,3) default 0 check (returned_quantity >= 0),
  notes text,
  allocated_by uuid references auth.users(id),
  issued_by uuid references auth.users(id),
  issued_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Function to check available stock before allocation
create or replace function public.check_available_stock(
  p_material_id bigint,
  p_requested_quantity numeric
)
returns boolean
language plpgsql
as $$
declare
  v_current_stock numeric;
  v_allocated_stock numeric;
  v_available_stock numeric;
begin
  -- Get current stock from material_master
  select coalesce(quantity, 0) into v_current_stock
  from public.material_master
  where material_id = p_material_id;
  
  -- Get total allocated (reserved + issued - returned)
  select coalesce(sum(allocated_quantity - returned_quantity), 0) into v_allocated_stock
  from public.material_allocations
  where material_id = p_material_id
    and status in ('Reserved', 'Issued', 'Partially Issued');
  
  -- Calculate available stock
  v_available_stock := v_current_stock - v_allocated_stock;
  
  -- Return true if enough stock available
  return v_available_stock >= p_requested_quantity;
end;
$$;

-- Function to update material stock after allocation
create or replace function public.update_material_stock_on_allocation()
returns trigger
language plpgsql
as $$
begin
  -- When issuing materials, reduce the stock
  if new.status = 'Issued' and (old.status is null or old.status != 'Issued') then
    update public.material_master
    set quantity = quantity - new.issued_quantity
    where material_id = new.material_id;
  end if;
  
  -- When returning materials, increase the stock
  if new.returned_quantity > coalesce(old.returned_quantity, 0) then
    update public.material_master
    set quantity = quantity + (new.returned_quantity - coalesce(old.returned_quantity, 0))
    where material_id = new.material_id;
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_update_material_stock on public.material_allocations;
create trigger trg_update_material_stock
after insert or update on public.material_allocations
for each row execute function public.update_material_stock_on_allocation();

-- Updated at trigger
drop trigger if exists trg_material_allocations_updated_at on public.material_allocations;
create trigger trg_material_allocations_updated_at
before update on public.material_allocations
for each row execute function public.set_updated_at();

-- Indexes
create index if not exists idx_material_allocations_material on public.material_allocations(material_id);
create index if not exists idx_material_allocations_project on public.material_allocations(project_id);
create index if not exists idx_material_allocations_status on public.material_allocations(status);
create index if not exists idx_material_allocations_date on public.material_allocations(allocation_date);

-- RLS policies
alter table public.material_allocations enable row level security;

drop policy if exists "material_allocations_select_auth" on public.material_allocations;
create policy "material_allocations_select_auth"
on public.material_allocations for select
to authenticated
using (true);

drop policy if exists "material_allocations_insert_auth" on public.material_allocations;
create policy "material_allocations_insert_auth"
on public.material_allocations for insert
to authenticated
with check (true);

drop policy if exists "material_allocations_update_auth" on public.material_allocations;
create policy "material_allocations_update_auth"
on public.material_allocations for update
to authenticated
using (true)
with check (true);

drop policy if exists "material_allocations_delete_auth" on public.material_allocations;
create policy "material_allocations_delete_auth"
on public.material_allocations for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
