-- Excess Materials Tracking
-- Track surplus materials returned to store for reuse

create table if not exists public.excess_materials (
  excess_id bigint generated by default as identity primary key,
  material_id bigint references public.material_master(material_id) on delete restrict not null,
  source_project_id bigint references public.projects(project_id) on delete set null,
  source_allocation_id bigint references public.material_allocations(allocation_id) on delete set null,
  quantity numeric(12,3) not null check (quantity > 0),
  condition text default 'Good' not null check (condition in ('Excellent', 'Good', 'Fair', 'Damaged')),
  return_date date default current_date not null,
  location text,
  status text default 'Available' not null check (status in ('Available', 'Reserved', 'Reused', 'Scrapped')),
  reused_in_project_id bigint references public.projects(project_id) on delete set null,
  reused_at timestamp with time zone,
  notes text,
  returned_by uuid references auth.users(id),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Function to add excess material to available stock
create or replace function public.add_excess_to_stock()
returns trigger
language plpgsql
as $$
begin
  -- When material is returned and marked as available, add to material master stock
  if new.status = 'Available' and new.condition in ('Excellent', 'Good', 'Fair') then
    update public.material_master
    set quantity = quantity + new.quantity
    where material_id = new.material_id;
  end if;
  
  -- When material is reused, reduce from available stock
  if new.status = 'Reused' and (old.status is null or old.status != 'Reused') then
    update public.material_master
    set quantity = quantity - new.quantity
    where material_id = new.material_id;
  end if;
  
  return new;
end;
$$;

drop trigger if exists trg_add_excess_to_stock on public.excess_materials;
create trigger trg_add_excess_to_stock
after insert or update on public.excess_materials
for each row execute function public.add_excess_to_stock();

-- Updated at trigger
drop trigger if exists trg_excess_materials_updated_at on public.excess_materials;
create trigger trg_excess_materials_updated_at
before update on public.excess_materials
for each row execute function public.set_updated_at();

-- Indexes
create index if not exists idx_excess_materials_material on public.excess_materials(material_id);
create index if not exists idx_excess_materials_source_project on public.excess_materials(source_project_id);
create index if not exists idx_excess_materials_status on public.excess_materials(status);
create index if not exists idx_excess_materials_condition on public.excess_materials(condition);

-- RLS policies
alter table public.excess_materials enable row level security;

drop policy if exists "excess_materials_select_auth" on public.excess_materials;
create policy "excess_materials_select_auth"
on public.excess_materials for select
to authenticated
using (true);

drop policy if exists "excess_materials_insert_auth" on public.excess_materials;
create policy "excess_materials_insert_auth"
on public.excess_materials for insert
to authenticated
with check (true);

drop policy if exists "excess_materials_update_auth" on public.excess_materials;
create policy "excess_materials_update_auth"
on public.excess_materials for update
to authenticated
using (true)
with check (true);

drop policy if exists "excess_materials_delete_auth" on public.excess_materials;
create policy "excess_materials_delete_auth"
on public.excess_materials for delete
to authenticated
using (true);

notify pgrst, 'reload schema';
